### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [Linaro/squad#1020]
https://hosted.weblate.org/projects/squad/core/#information specifies
"GNU Affero General Public License v3.0 only", whereas it should "or later", as per

https://github.com/Linaro/squad/blob/373cd5e97ebb702d869f7e1881c9973b26ce154d/squad/frontend/templates/django/rest_framework/api.html https://github.com/Linaro/squad/blob/373cd5e97ebb702d869f7e1881c9973b26ce154d/squad/frontend/templates/squad/base.jinja2
and specifically for translations https://github.com/Linaro/squad/blob/373cd5e97ebb702d869f7e1881c9973b26ce154d/squad/frontend/locale/django.pot

this can be done in https://hosted.weblate.org/settings/squad/core for admins :)

**Comment by chaws** [comment]
Thanks for raising this issue!

@terceiro I don't I have access to that, could you change that?

**Comment by terceiro** [comment]
fixed. 

@chaws added you as admin as well
