### ISSUE TITLE
Confidence UI feature

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#1026]
Here is the current layout. Please provide feedback. Thanks!

![127 0 0 1_8000_lkft_linux-stable-rc-4 14-oe_build_v4 14 74_failures_](https://user-images.githubusercontent.com/39019449/152174567-62f5e7c8-f2e4-4656-b9c8-236e7cee4d56.png)

Open question about defaults
If a test does not have the maximum number we want for confidence, should we just compute the confidence anyways using the data we have?

**Comment by mrchapp** [comment]
Yes.
