### ISSUE TITLE
Relicensing SQUAD under the GPLv3

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#1058]
Dear contributors,

We (Linaro) intend to relicense SQUAD from the GNU Affero General Public License version 3 or later (AGPLv3+)  to the GNU General Public License version 3 or later (GPLv3+)

We need that all non-Linaro contributors who made non-trivial contributions (e.g. ones that qualify for copyright) to agree with this:

- [x] `bonnemainsnathan@gmail.com` (French translation)
- [ ] `epost@anotheragency.no` (Norwegian translation)
- [x] `j.lavoie@net-c.ca` (French translation)
- [x] `milosz.wasilewski@foundries.io` (code changes)
- [ ] `simonpicot06@gmail.com` (French translation)
- [x] `ssantos@web.de` (Portuguese translation)

cc @NathanBnm @comradekingu  @mwasilew @s-pct @SantosSi we need your agreement to go ahead with this. Please leave a  comment below with your consent.

**Comment by comradekingu** [comment]
Any reason why? The GPLv3+ has fewer protections. Most notably it doesn't apply for distribution over a network.
