### ISSUE TITLE
cannot add annotations to builds

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#1066]
When I try to add an annotation, I get a generic user message and I can't proceed.

![image](https://user-images.githubusercontent.com/30027/184421728-55b022c9-9f94-40bc-84c8-d42eb25e9f3b.png)

**Comment by terceiro** [comment]
FWIW I tried this on a develoment instance and it just worked.

**Comment by chaws** [comment]
This was fixed in https://github.com/Linaro/squad/commit/1c4ef0e7d078002ae459e559ae5f547da1a6e377
