### ISSUE TITLE
Project counts at the home page are (very) wrong

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#1074]
![image](https://user-images.githubusercontent.com/30027/188174009-d85fb6f1-b938-449f-b336-4f22884e9e6d.png)

e.g. notice how it says "Linaro QA services team" has 108 projects, when in fact it has only 2:

![image](https://user-images.githubusercontent.com/30027/188174324-339386ec-e260-438c-b985-8d10385db5a3.png)

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad/commit/3d43a0948b699ea7702641e4d62f0fecf5aa1fec
