### ISSUE TITLE
null value in column "fetch_attempts" violates not-null constraint

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#148]
```
IntegrityError at /api/submitjob/lkft/android-hikey-linaro-4.9-oe/v4.9.61-638631-g83e9f5e022bc/hi6220-hikey
null value in column "fetch_attempts" violates not-null constraint
```

I guess this comes from missing migration to provide default values for existing backends.

**Comment by terceiro** [comment]
`fetch_attempts` has a default value. This is caused by the frontend not reloading correctly on upgrades, i.e. the database was migrated, but since the frontend didn't reload correctly, it didn't get the default value that is specified in the model definition.

**Comment by mwasilew** [comment]
Does it mean it will go away on it's own? I checked the db yesterday and all objects had the proper fields.

**Comment by terceiro** [comment]
yes. what I need to fix if making sure that the web frontend reloads properly on upgrades.

**Comment by terceiro** [comment]
but since there was a full restart since then, yes, this specific issue is fixed
