### ISSUE TITLE
Feature request: Project Badges

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#162]
Provide a http://shields.io/ style embeddable badge for a given project.

i.e. something like this. short label:
![](https://img.shields.io/badge/test-100%25%20pass-brightgreen.svg)
![](https://img.shields.io/badge/test-99%25%20pass-yellow.svg)

longer label:
![](https://img.shields.io/badge/test-5507%20pass%2C%20508%20skip%2C%204%20fail-red.svg)

It should show the most recent *completed* build.

**Comment by danrue** [comment]
I would be inclined to do green for 0 fails, and red for >0 fails. But maybe we have a yellow for some low threshold of failures.

**Comment by danrue** [comment]
Here's the concept I'm going for: 

![screenshot from 2018-01-05 15-40-27](https://user-images.githubusercontent.com/409011/34629711-cf6fca14-f22e-11e7-9042-ae0e186d2bd2.png)

**Comment by mwasilew** [comment]
The rows represent "environments" from squad point of view. I guess it's OK to have a separate badge for each env. We don't (yet) have information about builds, so only tests data would be available. If jenkins can give the badge for build, the table would be possible.

**Comment by danrue** [comment]
The build part is already possible in jenkins - the results in the screenshot for builds were live results at the time of the screenshot. Good point about the environments - I agree that I think we'll need a separate badge for each. Perhaps an interface like:

* https://qa-reports.linaro.org/lkft/linux-stable-4.14-oe/badge (overall project badge)
* https://qa-reports.linaro.org/lkft/linux-stable-4.14-oe/badge?environment=x86_64 (x84_64 specific results)

Note it could also be in a different namespace:
* https://qa-reports.linaro.org/badge?group=lkft&project=linux-stable-4.14-oe&environment=x86_64

**Comment by mike-holmes-linaro** [comment]
I believe a tie in with 96Boards that uses these tokesn would benefit both projects

**Comment by mwasilew** [comment]
@mike-holmes-linaro could you elaborate a bit more? I don't quite understand the suggestion.

**Comment by mike-holmes-linaro** [comment]
Dan has a better grasp than I on the details, but 96Boards have a SW compliance statement https://www.96boards.org/compliance/#Software.
"
It is strongly recommended that a 96Boards product achieves upstream kernel software support as defined below:

Level 1 – boot from upstream mainline kernel to a UART or USB console, or
Level 2 – boot from upstream kernel with full board functionality Hardware accelerators such as GPUs may be disabled, but the relevant function should operate – for example a frame buffer for graphics output, or
Level 3 – boot from upstream kernel with full board functionality Hardware accelerators such as GPUs are enabled with binary user space libraries, or
Level 4 – boot from upstream kernel with full board functionality with all hardware specific code (including any required user space libraries) available as open source

A 96Boards product shall support at least one of the following kernels:

An unmodified kernel.org mainline, stable or longterm (latest two releases) kernel. Note: Upstream mainline support is a 96Boards program goal
A Linaro-supported kernel with additional published patches against a kernel.org mainline, stable or longterm (latest two releases) kernel
A Linaro-supported kernel with additional published patches against an AOSP release kernel (latest two letter releases) or the latest AOSP current kernel
A vendor-supported kernel using any of the above kernel versions
"
It would be good if a tag  can be added to the 96Boards site proving that  the requirements are met if that board happens to run LKFT, the levels may even be detected by looking at the suites that pass possibly.

**Comment by mwasilew** [comment]
I think this request is about sth different. It's asking for HTML snippet + API that would generate 'pass rate badge' for the project. You'll still need to use it in some other place though. So in order to implement what you ask for we would have to have:
 - projects setup for each of the 96boards
 - test suite that implements the compliance spec
 - builds created for the boards (software actually changing).

AFAIK nothing of that is in place.

**Comment by mwasilew** [comment]
I got sth like this with shields.io:
https://img.shields.io/badge/dynamic/json.svg?label=mainline&url=https%3A%2F%2Fqa-reports.linaro.org%2Fapi%2Fbuilds%2F7760%2Fstatus%2F&query=%24.tests_pass&prefix=passed%3A%20
I guess we can just expose the proper string for a project and corresponding colour hex and shields.io will do the rest.

**Comment by danrue** [comment]
I think that would work. Can we document some examples in squad so that this functionality is easy to find and use?

**Comment by mwasilew** [comment]
PR#291 contains both options - shields.io (which doesn't offer dynamic colours at the moment) and standalone badge.

**Comment by mwasilew** [comment]
Badges are already available in production. Closing.
