### ISSUE TITLE
sort metadata on emails

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#166]
Imported from https://projects.linaro.org/browse/QA-1744
right now the metadata items will be more or less displayed in random order, based on the sorting in python dictionaries. we should probably pre-sort those and return a list of tuples (think .items()). however we need to take into account that custom templates might be assuming metadata is a dict so there will be a API break there.

**Comment by terceiro** [comment]
this has ben fixed in 3b58cd70023190c3bbbf01e31c42599c8663f352

**Comment by terceiro** [comment]
and, in the end, there was no API break since an OrderedDict looks and quacks like a dict
