### ISSUE TITLE
store test log snippet with test result

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#173]
Imported from https://projects.linaro.org/browse/QA-1729
When test result is recorded it should be possible to record the snippet of the log file that is associated with that test. At minimum we should log the line from LAVA log that provides the test result. In most cases this will not be enough.

milosz.wasilewski:
> I planned to start working on this next week. What's your plan/idea? I thought about creating a plugin for each test suite. I can't see any other solution right now.

antonio.terceiro:
> ah! I was organizing my board, and I saw this one unassigned so I took it. I don't have specific plans, feel free to take it.
> 
> I will take the REST API part (there was no card so I created one)

**Comment by mwasilew** [comment]
Plugins for CTS/VTS and LTP were created here: https://github.com/linaro/squadplugins

**Comment by danrue** [comment]
I agree the squad part of this change is complete.

**Comment by terceiro** [comment]
agreed
