### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#175]
Imported from https://projects.linaro.org/browse/QA-1719
The goal of this story is to provide support for pagination across squad UI. The most urgent feature is to support pagination in test results views. There might be a lot test results and current approach sometimes results in db timeouts when fetching data. 

Proposal: use django-rest-framework to reduce some backend work. The framework already implements pagination and some other useful features (searching, filtering)

**Comment by mwasilew** [comment]
I think this is already delivered. The only place without pagination is comparison view and it's going to be redesigned. @terceiro, @danrue any objections to close this ticket?

**Comment by terceiro** [comment]
agreed
