### ISSUE TITLE
monitor build/boot/test workflow

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#177]
Imported from https://projects.linaro.org/browse/QA-1713
In order to monitor the full path from code change to test results, squad should include support for build success/failure. All other data is already available (boot test is just another test result).

 

Currently we're only working with jenkins, so jenkins integration is the target of this story. One possible solution is to have jenkins call an API in squad to inform the build started. After that, build changes and result can be polled from jenkins. There might be however a way to subscribe to jenkins job for changes. This needs to be explored.

 

Presentation of the feature should be like online pizza order diagram. The 'version' of the project should go through stages - build, test, reporting. Unfortunately boot testing can't be separated at this point as LAVA only reports boot test results after all other testing is done.

 

Deliverables in this story:

 - jenkins integration proposal (either part of the build script or some jenkins callback API)

 - squad API to accept jenkins callback (or part of the build script callback)

 - jenkins backend implementation to poll jenkins for build status/progress

 - UI presenting stages of the progress for software 'version'

**Comment by chaws** [comment]
We currently have an [endpoint](https://github.com/Linaro/squad/commit/8588341582c0ac395e3c3c83126ef4ccdd99096e) to allow builds to be created by a separate api call. The UI for that is a spinning gear that shows a build being built or being booted/tested. Should we improve the UI or this is enough to close the issue?

**Comment by mwasilew** [comment]
Also LKFT guys implemented the jenkins call for each build. I think this can be closed now.
