### ISSUE TITLE
qa-reports: import existing data from art-reports

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#188]
Imported from https://projects.linaro.org/browse/QA-1629
the import should be automated and repeatable: we should be able to do it several times, including but not limited to on initial tests, for demonstrating to the ART team, and right before flipping the switch from art-reports to qa-reports.

antonio.terceiro:
> we will first make the ART automation submit to qa-reports in parallel, then do a single import and that is it

milosz.wasilewski:
> Dependency issue QA-1637 resolved with resolution Delivered.

**Comment by terceiro** [comment]
I have this working OK locally. When we start to receive data from new builds (#206), I can do ahead and import the previous builds.

**Comment by mwasilew** [comment]
I'm planning to have the new build data patches next week.

**Comment by terceiro** [comment]
this has been done
