### ISSUE TITLE
handle "patched" builds

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#194]
Imported from https://projects.linaro.org/browse/QA-1550
"patched" builds is a fundamental aspect of ART-reports. With then, we can compare benchmark results of a build produced from a patch sent to gerrit with a given baseline build, produced from master/trunk. these results are then posted as gerrit review comments on the patch review.

The initial idea to implement this in squad is as follows: every project will have an extra, hidden/private project that is used as a container for those patched builds.The original project is used as baseline, and the patch project can be used to list patches from.

Baseline and patched builds must submit a field that is used to match them together (e.g. the manifest hash we have in ART-reports)

**Comment by terceiro** [comment]
this has been implemented in #275
