### ISSUE TITLE
display range of values in charts

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#195]
Imported from https://projects.linaro.org/browse/QA-1548
Right now the charts display only the central measure (mean) of metrics. It should also display the full range, as in ART-reports.

Note: at this moment, Charts.js does NOT support this, so it might be needed to switch chart library to be able to do this.

**Comment by chaws** [comment]
@mwasilew I think Charts.js kinda have a support for that nowadays: https://www.chartjs.org/samples/latest/charts/area/line-datasets.html

**Comment by mwasilew** [comment]
it was worth to wait :P
