### ISSUE TITLE
record submission details

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#202]
Imported from https://projects.linaro.org/browse/QA-1495
Record the token, ip address and similar data to recognize from the data comes from.

**Comment by mwasilew** [comment]
@terceiro do you think using https://github.com/justquick/django-activity-stream is a good idea to implement this feature?

**Comment by terceiro** [comment]
@mwasilew I don't think we need that level of detail. this issue is about something way simpler. but also we never really had the need for this, so maybe it's not even worth implementing it
