### ISSUE TITLE
submit ART data to qa-reports in parallel with art-reports

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#206]
Imported from https://projects.linaro.org/browse/QA-1435

**Comment by chaws** [comment]
Maybe it's similar to https://github.com/Linaro/squad/issues/188

**Comment by mwasilew** [comment]
I think the difference is that #188 talks about one time action of migrating existing art-reports data while this ticket covers migrating the 'new' data feeds case.

**Comment by mwasilew** [comment]
This has been completed.
