### ISSUE TITLE
support for external configuration files

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#210]
REST API allows to add/update objects in the database. This feature can be used to keep track of Project, Group and EmailTemplate settings. The idea is that configuration for them is kept in some markup files (YAML?) and applied to the squad instance when the files change. The concept is similar to jeknins and jenkins-job-builder.

**Comment by danrue** [comment]
Using yaml variable substitution as Antonio proposed would make this a pretty straight forward yaml file plus a python parse and POST script.

{noformat}
yaml variable substitution:     
>>> import yaml                 
>>> data = """
... foo: &foo
...   - 1
...   - 2
... bar: *foo
... """
>>> yaml.load(data)
{'foo': [1, 2], 'bar': [1, 2]}
{noformat}

**Comment by mwasilew** [comment]
Fixed with #262
