### ISSUE TITLE
Link incorrect in test job table

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#228]
![screenshot from 2018-02-08 12-02-48](https://user-images.githubusercontent.com/409011/36262652-b1e6fbec-122d-11e8-81c5-f2ab3dd1469a.png)

The "Test run #113408" link in the top row of the screenshot is incorrect. It should link to "Testrun #114098".  This happens when resubmitting a test job.

**Comment by mwasilew** [comment]
At this point the test run doesn't exist so IMHO there should be no link to test run.

**Comment by danrue** [comment]
That's fine. It took me many times of absent mindedly clicking on that (wrong) link and getting really confused before realizing what was happening. All I really wanted was the lava link anyway, which I discovered is what the first link goes to, though it was not obvious to me.
