### ISSUE TITLE
Remove redundant data from the build metadata

### ISSUE THREAD

**Issue by situmam** [Linaro/squad#235]
If you look here: https://qa-reports.linaro.org/lkft/linux-stable-4.14-oe/ you will see a list of the job ids and in another row, a list of the URL for these IDs. 
This is redundant. I suggest we combine both by linking the job ID number to the URL.

**Comment by mwasilew** [comment]
We would need to consider these as "special" metadata which I'm a bit reluctant to do. @terceiro any opinion on that?

**Comment by terceiro** [comment]
just as we have a list of "important" metadata that are shown by default while the rest is hidden, we could have a list of metedata keys that are never to be displayed. But we could as well use the URLs as job_ids directly on the jenkins side, in which case we don't need to do anything on que squad side.

**Comment by mwasilew** [comment]
These metadata items are artificially generated in squad:
https://github.com/Linaro/squad/blob/master/squad/ci/models.py#L78
https://github.com/Linaro/squad/blob/master/squad/ci/models.py#L81

**Comment by terceiro** [comment]
ok. so, do we want to have job_id if and only if job_url is not present?

**Comment by mwasilew** [comment]
I don't have a strong opinion on that. We'll need to check whether any of these is used somewhere internally. If it's not mandatory to have job_id, than we can remove it.

**Comment by situmam** [comment]
@mwasilew did you find out if the job_id is used?

**Comment by situmam** [comment]
An alternative approach to remove the job_id and job_url from the metadat entirely and have it linked from the test results directly (the number next to the gear box icon in the test results table). 
https://send.firefox.com/download/eedf377326/#ItvbFUPxXFAddro7JZdEDw

That makes it that much more easier to get at the data related to a passed or failed test.

**Comment by mwasilew** [comment]
@situmam there is a separate page for metadata. I think this ticket can be closed. Any objections?
