### ISSUE TITLE
List the groups first on the home page

### ISSUE THREAD

**Issue by situmam** [Linaro/squad#236]
Right now, the group name is repeated with every job listed on the home page. In the case of qa-reports.linaro.org, the home page is quite cluttered. It would be much cleaner to have the home page default to the list of groups and have their projects listed as bullets. Adding expand/collapse visual UI would be ideal as well and making that persistent across sessions is ideal.

**Comment by mwasilew** [comment]
I think we discussed this in the past and there was no conclusion. I agree it would make sense to optimize somehow.

**Comment by danrue** [comment]
And if groups has a displayed description field, perhaps we could use it to explain 'lkft-staging' and make it publicly available.

**Comment by situmam** [comment]
That's an awesome idea.

**Comment by terceiro** [comment]
as  the number of projects grow, listing every project in the home page starts to be tricky. maybe we should display _only_ the groups in the home page, and list the projects in the group page?
