### ISSUE TITLE
Add support for different recipients lists based on test status

### ISSUE THREAD

**Issue by ndechesne** [Linaro/squad#242]
Instead of sending all emails to the same recipients lists, is it possible to maintain 2 lists of recipients:
* "default" : list of recipients willing to receive all emails, with or without regression
* "regression": list of recipients willing to receive email *only* when a regression was found. When a regression is found, this list of recipients is concatenated with the 'default' list.

that would allow non LKFT core people to only monitor regressions.

**Comment by danrue** [comment]
I interpret this request to be "make notification strategy a per-recipient choice rather than a project choice".

**Comment by mwasilew** [comment]
I guess this is correct approach (per-recipient settings). This idea was on the backlog for some time (I didn't find a ticket though).

**Comment by ndechesne** [comment]
yes, per recipient choice, but as discussed on IRC, please make sure to send 1 email with a consolidated list of all needed recipients, so that reply-all does a good job.

**Comment by ndechesne** [comment]
any update on this request?

**Comment by mwasilew** [comment]
No progress so far. I'm trying to simplify subscriptions with external config file (stored in version control) but that is progressing very slowly (a lot of corner cases). If this feature is important we can prioritize it for July.

**Comment by ndechesne** [comment]
as you know we had subscribed our ML to get notifications, but after several weeks/months, the feedback is that what we get looks more like spam than anything useful, so we've removed our ML to not get notifications.. I guess if we find it spammy, we might not be the only ones.. 

a good notification system by email seems very important for this tool. Ideally a recipient should decide to watch for regression only (and in fact.. i thought about this one after I made this issue.. it would be nice to watch only regressions on specific boards!).

**Comment by mwasilew** [comment]
@stevanradakovic could you look into it?
