### ISSUE TITLE
Allow users to filter in/out some board

### ISSUE THREAD

**Issue by ndechesne** [Linaro/squad#245]
while some users might appreciate the overall status for all boards at a specific commit, there are developers who will be interested in trends/status over time/builds for a specific board (or set of boards).

right now it is hard to look at results/data for a specific board when navigating on qa-reports. 

in fact it is even not obivous on which platform tests were run, e.g. if you go to 

https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v4.16-rc5-4-gfc6eabbbf8ef/

it would be nice to have 'boards' in metadata, and if we could click on a board and filter out only relevant information for this board.. e.g. display only lava tests for this board, only results for it.. 

and we could do it similarly at the 'project' level, e.g. https://qa-reports.linaro.org/lkft/linux-mainline-oe/, it could list all boards that have been used in this project...

**Comment by mwasilew** [comment]
I discussed very similar feature with Anders today. My plan is to add 'filter/search' widget to project and build view. This way we'll be able to display more with easier navigation. I'll make this high priority.

**Comment by mwasilew** [comment]
The filter already works. It's probably not obvious that it accepts several fields:
https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v4.16-rc5-4-gfc6eabbbf8ef/#!?filter-tests=dragonboard

**Comment by ndechesne** [comment]
ah, nice. so it would be nice to be able to 'click' on a board and show relevant test, from the main page. is that doable?

**Comment by mwasilew** [comment]
Do you mean filter all failed tests for the board (environment)?

**Comment by mwasilew** [comment]
ouch, we broke the filter feature with @amrohassaan's UI changes.

**Comment by terceiro** [comment]
pffff. while looking at optimizing the build page, I noticed it is *really* heavy. also I realized that I don't really like the "click through" to show/hide data ...

I think we should redesign that page as a comparison table (similar to the test history) where you show environments as columns, and suites as rows, with counts of pass/fail/skip on each cell ...

**Comment by chaws** [comment]
So, this issue has been open for a while now and lots of things have changed.

The build page has been optimized and now it loads much quicker.

@ndechesne , FYI right now you can see Build results by boards (e.g. environments) where you can see what you want.

I'm closing this, but please reopen it if that's not what you requested
