### ISSUE TITLE
add UI for self-service editing of groups and of projects by group admins

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#248]
users should be able to create their own groups and projects.

when editing a project, group and slug need to be read-only, while most of the other fields should probably be editable.

**Comment by mwasilew** [comment]
hmm, should we just rely on the 'configuration tool' with files stored in version control.

**Comment by terceiro** [comment]
well the update tool is useful for us as admins, but IMO we should allow
the project owners to update them by themselves ... think of a squad
site as "github" for QA data, if we have the necessary UI people can do
everything by themselves: they create a group/project, set up their own
CI to post data, and admins don't need to get involved.

of course, at the moment this is low priority for Linaro, but that is
something I would like to have eventually.

**Comment by chaws** [comment]
Closed with https://github.com/Linaro/squad/pull/490
