### ISSUE TITLE
When renaming a build version, test jobs are disassociated

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#255]
I went here and changed the version of a build (I would just delete it, but in the past I've tried and it usually times out and fails to delete), so that I can run it again from scratch and not have the results mixed in:
![screenshot from 2018-04-13 09-23-12](https://user-images.githubusercontent.com/409011/38740107-5022898e-3efc-11e8-9aa5-ab496ec4aea1.png)

Then when I went to view the renamed build, all test jobs are gone:
![screenshot from 2018-04-13 09-24-28](https://user-images.githubusercontent.com/409011/38740168-7ad7fe70-3efc-11e8-86d3-71767ca39a2c.png)

Note that test results are still there, but the list of test jobs is no longer shown. It seems that something is relying on the build name rather than the foreign key.

**Comment by mwasilew** [comment]
TBH I don't remember why, but this was 'by design'. This is part of TestJob model. @terceiro any idea why this is a CharField rather than a ForeignKey?
```
build = models.CharField(max_length=100)
```

**Comment by terceiro** [comment]
IIRC I didn't want to have the build created before being sure the test job produced valid results, but we can revisit that

**Comment by amrohassaan** [comment]
PR#391 submitted for this bug.
