### ISSUE TITLE
Add 'regressions' indication on the project summary page

### ISSUE THREAD

**Issue by ndechesne** [Linaro/squad#284]
In the project summary page, we list all builds , and we clearly see the number of tests for each builds, and the number of pass/failed. Can you please add an indicator to add the number of regressions as well? The data is available in the email report, but having it in the GUI would be very useful as well.

**Comment by mwasilew** [comment]
It might be a bit expensive as regressions are calculated at the time of composing email. They're not saved in the DB. It is possible though and not too hard to do.

**Comment by ndechesne** [comment]
given that we are really trying to find regressions every day (more than just trying to find 'bugs'), I would think tracking regressions in the DB would be a nice improvement.
