### ISSUE TITLE
Be able to specify baseline when using email api

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#303]
When calling the API like so:

https://qa-reports.linaro.org/api/builds/8275/email/

Note the line "compared to build v4.14.56-93-gec86d5e19e14".

Squad chooses the baseline (build v4.14.56-93-gec86d5e19e14 in this case) by naively using the previous build. However, my API client is able to determine a better baseline because it has knowledge of the project.

If the email endpoint allowed a 'baseline' build to be specified, perhaps like so: "https://qa-reports.linaro.org/api/builds/8275/email?baseline=8156", then the fixes and regressions that an email report produces would be much more useful.

**Comment by mwasilew** [comment]
I think I can do that with minimal changes to Notification class.

**Comment by mwasilew** [comment]
@danrue I have the code for basic use case. Now what should happen in case of:
 - build comes from different project (currently it is silently ignored)?
 - build doesn't exist - given ID is invalid (currently it is silently ignored)?

I can return 500 in both cases if that is more helpful.

**Comment by mwasilew** [comment]
Here is the branch with this feature https://github.com/mwasilew/squad/tree/api_email_custom_baseline

**Comment by danrue** [comment]
Here's my $.02 on behavior:

- build comes from different project (currently it is silently ignored)?

Since SQUAD is able to compare builds across projects already, this should be allowed. Often it is useful to compare builds across projects (and even groups). If it's rubbish or not should be left to the user to decide, not squad.

- build doesn't exist - given ID is invalid (currently it is silently ignored)?

500

**Comment by mwasilew** [comment]
OK, I'll do as you propose. Or at least try. I'm not sure what happens when we try to compare builds from 2 different projects.
