### ISSUE TITLE
Test results filter broken on builds page

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#320]
The 'Test results' filter on the build page no longer works.

For example, at https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v4.18-10986-g778a33959a8a/, I expect the attached screenshot to only show me kselftest results.

![screenshot from 2018-08-21 11-15-40](https://user-images.githubusercontent.com/409011/44414545-a5e58e00-a533-11e8-89a1-7a8f9f669101.png)

**Comment by mwasilew** [comment]
This will be fixed by #316

**Comment by mwasilew** [comment]
#316 is merged. Filtering works on staging already.
