### ISSUE TITLE
KeyError: 'xfail' when generating email with known issues

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#341]
This is blocking adoption of known issues in LKFT. We've deleted all LKFT known issues in the meantime.

When generating an email that contains a known issue, the following traceback is observed:

https://gist.github.com/danrue/9fb066f948d56b15b2ca820bfe14df23#file-gistfile1-txt

**Comment by mwasilew** [comment]
@danrue could you share the template?

**Comment by mwasilew** [comment]
@danrue nevermind, I managed to reproduce it.
