### ISSUE TITLE
charts: Y axis changes all the time when scrolling the date slider

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#378]
this is confusing, and makes it harder to understand the data. IMO the Y should be fixed wrt the entire data set.

**Comment by stevanradakovic** [comment]
It was decided with @terceiro that we take no action on this one at the moment, as there are use cases where both behaviors of the Y axis are acceptable and there are no strong arguments for either implementation.

**Comment by chaws** [comment]
@stevanradakovic , closing this based on your last comment.
