### ISSUE TITLE
Refactor ng apps

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#401]
Stevan did a PR merging two ng-apps into a single one in build.js: https://github.com/Linaro/squad/pull/398

Then Terceiro suggested we should have a single ng-app per page, sharing controllers among each other

**Comment by stevanradakovic** [comment]
Just to expand on this, each controller should reside in separate .js file, so it can be easily shared between apps without too much overhead.

**Comment by mwasilew** [comment]
As a part of it I also would like to make sure csrf tokens are used in all JS calls. Right now it's not the case.
