### ISSUE TITLE
Append suite version next to suite name in testresults and hide it from metadata.

### ISSUE THREAD

**Issue by amrohassaan** [Linaro/squad#402]
This issue is created to reflect request in [LSS-83](https://projects.linaro.org/browse/LSS-83)

The goal of this issue is to implement SuiteVersion/SuiteMetadata presentation for Build and TestRun pages. Currently the versions are only presented in metadata table, but the entries might be hidden (using "important keys") so the information should be presented in the test suite table. 

As a bonus it might be a good idea to present the version of the Test in the test results page. Not mandatory for closing this ticket.

**Comment by amrohassaan** [comment]
@mwasilew I have created the issue you asked for here so i have it in my visual better than JIRA. Please verify the desc in summary title and edit the description as you see fit.

**Comment by chaws** [comment]
@amrohassaan was this issue related to this commit: https://github.com/Linaro/squad/commit/77ae315b85e3a7c7246099b3675438e5b14e09e0 ?

**Comment by amrohassaan** [comment]
> @amrohassaan was this issue related to this commit: [77ae315](https://github.com/Linaro/squad/commit/77ae315b85e3a7c7246099b3675438e5b14e09e0) ?

@chaws  yesir..this was a very old issue.
