### ISSUE TITLE
Add all test results filtering

### ISSUE THREAD

**Issue by situmam** [Linaro/squad#422]
If you have alot of test results (eg. CTS or VTS) , you will be hard pressed to find information about a specific test in the long list of tests [1] . It would be helpful to have a search box listed above the table of test results where you can type part of the name of the test and have it displayed.
  
[1] - https://qa-reports.linaro.org/android-lkft/aosp-master-tracking/build/1044/tests/

**Comment by mwasilew** [comment]
@situmam in the meantime you can already use the API as follows:
https://qa-reports.linaro.org/api/tests/?test_run__build__project__slug=aosp-master-tracking&test_run__build__version=1044&short_name__contains=test.core.test_metrics_data

available filters:
 - exact (no keyword)
 - startswith
 - contains
 - icontains (case insensitive contains)
