### ISSUE TITLE
Fixes UI incorrect

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#432]
kselftest/bpf_test_verifier_log is not a 'fix' in v4.19.10-45-g75803dcafdb3, as can be seen here: https://qa-reports.linaro.org/lkft/linux-stable-rc-4.19-oe/tests/kselftest/bpf_test_verifier_log?top=v4.19.10-45-g75803dcafdb3

Yet, it (and many others) are shown as fixes over and over again in https://qa-reports.linaro.org/lkft/linux-stable-rc-4.19-oe/ when hovering over the green check box icon.

![image](https://user-images.githubusercontent.com/409011/50182044-e54e9c00-02d3-11e9-955b-78a22748f6ca.png)

I believe this behavior was introduced in 0.56.

**Comment by stevanradakovic** [comment]
@danrue Hm I fail to see 'kselftest/bpf_test_verifier_log' in the attached image or in the UI when I hover. I only see 'kselftest/bpf_test_verifier' but this one has failed in multiple occasions so it shows up correctly afais. Can you please clarify?
