### ISSUE TITLE
create step by step instructions for setting up SQUAD with LAVA

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#441]
It turns out to be a hard task to set up SQUAD to work together with LAVA instance. SQUAD docs should contain step by step instructions that explain how to do that.

**Comment by chaws** [comment]
Would this also include a sample Jenkins instance or just LAVA & SQUAD?

**Comment by mwasilew** [comment]
I thought about LAVA and SQUAD as this isn't obvious. There is a thread about that in the ML:
https://lists.linaro.org/pipermail/squad-dev/2019-January/000049.html

**Comment by chaws** [comment]
Please check: https://github.com/Linaro/squad/pull/443
