### ISSUE TITLE
incompatibility with python 3.7

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#442]
From mailing list report:

> When submitting a job, the squad service will return an error message saying :
> AttributeError: module 're' has no attribute '_pattern_type'
> this error occurs in the file "~/.local/lib/python3.7/site-packages/celery/app/routes.py"
> 
> This can be work arounded by adding this line right after "import re":
> re._pattern_type = re.Pattern
> 
> Hope this helps.

Origin: https://lists.linaro.org/pipermail/squad-dev/2019-January/000062.html

**Comment by terceiro** [comment]
we can work around that in squad, but this is actually something that needs to be fixed in celery

**Comment by chaws** [comment]
It seems to be fixed already: https://github.com/celery/celery/pull/4902.  
Celery doesn't support 3.7 though

**Comment by chaws** [comment]
Celery now supports Python 3.7: https://github.com/celery/celery/blob/master/README.rst#what-do-i-need and they fixed that issue: https://github.com/celery/celery/pull/4902/commits/3c68cd4032e4dc3713110a038f11f4a4a60c944f

It shouldn't raise that error message anymore.
