### ISSUE TITLE
Add query result limit to api/data

### ISSUE THREAD

**Issue by stevanradakovic** [Linaro/squad#462]
Api calls from Google data studio time out in most cases because of large datasets. We should add support to limit the amount of data retrieved from api/data.

**Comment by danrue** [comment]
Here's an example qa-reports-based graph that I created manually by exporting the data as CSV and uploading it to google data studio. Will something like this be possible with the connector? https://datastudio.google.com/reporting/1bGoJkoThvFhe4GOmtgWoJfIITgekOsvu/page/jxNg

**Comment by mwasilew** [comment]
IIRC there was a limitation to query from one project. @stevanradakovic could you confirm/deny? :)

**Comment by stevanradakovic** [comment]
@mwasilew Yes, one project per view.
