### ISSUE TITLE
Feature request: Per-user email templates

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#464]
![image](https://user-images.githubusercontent.com/409011/51640418-08024f00-1f29-11e9-9ced-1d8df27cba32.png)

Now that we have per-user notification strategies, I wonder if it's also possible to have per-user email templates?

Our specific usecase: For linux -next, continue to send the full report as we are. In addition, send a kselftest-specific report to the kselftest mailing list. Anders has created an email template which filters out everything except the kselftest results. An example of this report can be seen at https://qa-reports.linaro.org/api/builds/12898/email/?template=12.

Thanks!

**Comment by mwasilew** [comment]
This is probably doable but there are downsides:
 - emails with different content can't be sent with all recipients in 'to' field
 - generating different email body for different recipients will increase load (this is already pretty heavy operation)

While I've no problem with a bit more load, the 1st issue might cause a problem or at least misunderstanding. If user signs up for a project notification with different template than project uses, his content has to be generated separately and 'to' field will only contain this user's email address. To get added to "everyone else's" notification he would have to subscribe to the same project twice, which we currently can't do.

TBH it sounds like asking for trouble, but we'll discuss it on Monday :)

**Comment by terceiro** [comment]
one way of mitigating this concern is having the UI for this feature provide a clear and visible enough warning that the user will be excluded from the general email.

TBH, I think that mailing several users in open cc: is already an anti-pattern anyway, and maybe we should get rid of that. For example, in the context of an open squad instance, a random user can subscribe to a project, and at the next notification, gain access to the emails addresses of whoever else is subscribed to that project.

**Comment by chaws** [comment]
@danrue , I'm closing this, please let us know if you have more questions to this regard.
