### ISSUE TITLE
"Too many SQL variables"

### ISSUE THREAD

**Issue by axelnxp** [Linaro/squad#470]
Error returned by squad-worker.
Occurs when trying to send email notification on a project.
In this project, I run full CTS/VTS, it's about 500k test cases for each build.

Full stack attached.

[log.txt](https://github.com/Linaro/squad/files/2827638/log.txt)

**Comment by terceiro** [comment]
@axelnxp I notice you are running this system against sqlite3, which is not recommended for production usage, specially when handling such large amount of data. There is nothing that we can realistically do to fix this, except for you switching to a more robust RDMS (postgresql)

**Comment by axelnxp** [comment]
Ok thank you, I will do so then :)
