### ISSUE TITLE
when following documentation example: "curl" never returns.

### ISSUE THREAD

**Issue by RafaGago** [Linaro/squad#478]
OS: Ubuntu 18 vanilla.
Revision: 948110b3425c6bc6fb02108b0de25cd7934065bb

I was just checking Squad and following the documentation. I install locally and run following the "Quick start" instructions on the documentation, then I create a user authentication token, a group, a project and do:

`curl --header "Auth-Token: MYTOKEN" --form tests='{"suite/test1": "pass", "suite/test2": "fail"}' --form metrics='{"suite/metric1": 21, "suite/metric2": 4}' --form metadata='{"job_id": "1"}' --form log='Hello log' --form attachment="Hello attachment" http://127.0.0.1:8000/api/submit/my-slug/my-project-slug/1/board
`

This was as instructed on the link below. I had to add "job_id" to the metadata.
https://squad.readthedocs.io/en/latest/intro.html#result-submit-ref-label

On the server I can see the build, but it shows as pending with that animated rotating wheel forever. curl never returns. Is this expected behavior?

**Comment by terceiro** [comment]
hi

there is a bit missing in the documentation: you need to have rabbitmq-server running. OTOH, it should indeed not hang forever. This is handled in #480
