### ISSUE TITLE
start squad with systemd

### ISSUE THREAD

**Issue by feine-moehre** [Linaro/squad#534]
I try to manage the squad (0.64.1) service with systemd on debian stretch. This is my squad.service file:

```
[Unit]
Description=Software Quality Dashboard
After=network.target

[Service]
Type=simple
User=squad
WorkingDirectory=/home/squad
ExecStartPre=env
ExecStart=/usr/local/bin/squad --bind <my-ip>:5000
Restart=on-failure
Environment=HOME=/home/squad
Environment="DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=squad:HOST=localhost:PASSWORD=<password>"
Environment=XDG_DATA_HOME=/home/squad/.local/share
[Install]
WantedBy=multi-user.target
```

These are the service messages from journalctl

```
May 20 10:45:28 systemd[1]: Starting Software Quality Dashboard...
May 20 10:45:28 env[9206]: LANG=en_GB.UTF-8
May 20 10:45:28 env[9206]: LANGUAGE=en_GB:en
May 20 10:45:28 env[9206]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
May 20 10:45:28 env[9206]: HOME=/home/squad
May 20 10:45:28 env[9206]: LOGNAME=squad
May 20 10:45:28 env[9206]: USER=squad
May 20 10:45:28 env[9206]: SHELL=/bin/bash
May 20 10:45:28 env[9206]: INVOCATION_ID=<....>
May 20 10:45:28 env[9206]: JOURNAL_STREAM=9:6058748
May 20 10:45:28 env[9206]: DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=squad:HOST=localhost:PASSWORD=<..>
May 20 10:45:28 env[9206]: SQUAD_ADMINS=<...>
May 20 10:45:28 env[9206]: XDG_DATA_HOME=/home/squad/.local/share
May 20 10:45:28 systemd[1]: Started Software Quality Dashboard.
May 20 10:45:29 squad[9207]: Operations to perform:
May 20 10:45:29 squad[9207]:   Apply all migrations: admin, auth, authtoken, ci, contenttypes, core, sessions
May 20 10:45:29 squad[9207]: Running migrations:
May 20 10:45:34 squad[9207]:   Applying core.0119_i18n...[2019-05-20 08:45:34 +0000] [9207] [INFO] Starting gunicorn 19.9.0
May 20 10:45:34 squad[9207]: [2019-05-20 08:45:34 +0000] [9207] [INFO] Listening at: http://<my-ip>:5000 (9207)
May 20 10:45:34 squad[9207]: [2019-05-20 08:45:34 +0000] [9207] [INFO] Using worker: sync
May 20 10:45:34 squad[9207]: [2019-05-20 08:45:34 +0000] [9265] [INFO] Booting worker with pid: 9265
```

If I start squad with `squad --bind  <my-ip>:5000`  on the terminal under user squad (the same like the service), squad starts and works normally. 

When I start the service via systemd, squad start under the given user and is also listen on the specified ip:port. BUT squad will not find the complete configuration. Is looks like an empty setup. 
I assume this is a misconfiguration. But I have no clue whts wrong. I use the same user and (hopefully) then same path.

The same way works for the worker, listener and scheduler.

**Comment by terceiro** [comment]
I can't see anything wrong with your seup ...

FWIW ours is similar, only with the environment coming from a single external file

```
[Unit]
Description=SQUAD: software quality dashboard
After=postgresql.service rabbitmq-server.service

[Service]
User=squad
Group=squad
PrivateTmp=yes
WorkingDirectory={{install_base}}
ExecStart={{install_base}}/bin/squad --timeout=60 --workers={{number_of_workers}} --fast --log-level DEBUG
ExecReload=/bin/kill -HUP $MAINPID
EnvironmentFile={{install_base}}/environment
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by feine-moehre** [comment]
This is weird. So I need more debug information. 
Using `--log-level DEBUG`  squad displays no path to database/files/secret etc. Where is the best location to display such information e.g. at startup?

**Comment by terceiro** [comment]
try applying this patch, and hitting /debug after starting the service via systemd:

```diff
diff --git a/squad/frontend/urls.py b/squad/frontend/urls.py
index 6aea443..a34c83f 100644
--- a/squad/frontend/urls.py
+++ b/squad/frontend/urls.py
@@ -18,6 +18,7 @@ group_and_project = (group_slug_pattern, slug_pattern)
 
 
 urlpatterns = [
+    url(r'debug$', lambda _: HttpResponse(repr(dict(settings.__dict__)), content_type='text/plain')),
     url(r'^favicon.ico$', lambda _: redirect(settings.MEDIA_URL + '/static/favicon.ico')),
     url(r'^robots.txt$', lambda _: HttpResponse("User-agent: *\nDisallow: /\n", content_type='text/plain')),
     url(r'^$', views.home, name='home'),
```

**Comment by terceiro** [comment]
or even better:

```diff
diff --git a/squad/frontend/urls.py b/squad/frontend/urls.py
index 6aea443..1b1efec 100644
--- a/squad/frontend/urls.py
+++ b/squad/frontend/urls.py
@@ -2,6 +2,7 @@ from django.conf import settings
 from django.conf.urls import include, url
 from django.http import HttpResponse
 from django.shortcuts import redirect
+from pprint import pformat
 
 from . import views
 from . import comparison
@@ -18,6 +19,7 @@ group_and_project = (group_slug_pattern, slug_pattern)
 
 
 urlpatterns = [
+    url(r'debug$', lambda _: HttpResponse(pformat(settings.__dict__), content_type='text/plain')),
     url(r'^favicon.ico$', lambda _: redirect(settings.MEDIA_URL + '/static/favicon.ico')),
     url(r'^robots.txt$', lambda _: HttpResponse("User-agent: *\nDisallow: /\n", content_type='text/plain')),
     url(r'^$', views.home, name='home'),
```

**Comment by feine-moehre** [comment]
With this patch I got: (the pprint didn't help)

{'SECURE_BROWSER_XSS_FILTER': False, 'STATICFILES_STORAGE': 'whitenoise.storage.CompressedManifestStaticFilesStorage', 'SESSION_SERIALIZER': 'django.contrib.sessions.serializers.JSONSerializer', 'LANGUAGE_CODE': 'en', 'DEFAULT_CHARSET': 'utf-8', 'LOCALE_PATHS': [], 'SECURE_HSTS_PRELOAD': False, 'ABSOLUTE_URL_OVERRIDES': {}, 'TEMPLATES': [{'APP_DIRS': True, 'OPTIONS': {'environment': 'squad.jinja2.environment', 'context_processors': ['django.template.context_processors.debug', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages'], 'extensions': ['jinja2.ext.i18n', 'jinja2.ext.with_']}, 'BACKEND': 'django.template.backends.jinja2.Jinja2', 'DIRS': ['/usr/local/lib/python3.5/dist-packages/squad/frontend/templates', '/usr/local/lib/python3.5/dist-packages/squad/core/templates', '/usr/local/lib/python3.5/dist-packages/squad/ci/templates']}, {'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/usr/local/lib/python3.5/dist-packages/squad/frontend/templates/django/']}], 'LANGUAGE_COOKIE_NAME': 'django_language', 'USE_I18N': True, 'SECURE_CONTENT_TYPE_NOSNIFF': False, 'DATABASES': {'default': {'NAME': 'squad', 'ENGINE': 'django.db.backends.postgresql_psycopg2', 'HOST': 'localhost', 'ATOMIC_REQUESTS': False, 'TEST': {'MIRROR': None, 'NAME': None, 'CHARSET': None, 'COLLATION': None}, 'CONN_MAX_AGE': 0, 'USER': 'squad', 'TIME_ZONE': None, 'AUTOCOMMIT': True, 'OPTIONS': {}, 'PORT': '', 'PASSWORD': 'my-password'}}, 'MEDIA_URL': '', 'FORCE_SCRIPT_NAME': None, 'SECURE_REDIRECT_EXEMPT': [], 'SESSION_COOKIE_NAME': 'sessionid', 'DEFAULT_INDEX_TABLESPACE': '', 'STATIC_URL': '/static/', 'SESSION_ENGINE': 'django.contrib.sessions.backends.db', 'CSRF_USE_SESSIONS': False, 'DEFAULT_TABLESPACE': '', 'SITE_NAME': 'SQUAD', 'ROOT_URLCONF': 'squad.urls', 'REST_FRAMEWORK': {'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'], 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.TokenAuthentication'), 'DEFAULT_FILTER_BACKENDS': ('rest_framework_filters.backends.DjangoFilterBackend', 'rest_framework.filters.OrderingFilter', 'rest_framework.filters.SearchFilter', 'squad.api.utils.DisabledHTMLFilterBackend'), 'PAGE_SIZE': 50, 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination'}, 'SECURE_SSL_HOST': None, 'SECURE_SSL_REDIRECT': False, 'PREPEND_WWW': False, 'LOGGING_CONFIG': 'logging.config.dictConfig', 'MEDIA_ROOT': '', 'CSRF_COOKIE_NAME': 'csrftoken', 'ALLOWED_HOSTS': ['my-host'], 'LANGUAGES': [('en', 'English'), ('pl', 'Polish')], 'LOGGING': {'handlers': {'console': {'formatter': 'myformatter', 'class': 'logging.StreamHandler'}, 'mail_admins': {'level': 'ERROR', 'class': 'django.utils.log.AdminEmailHandler'}}, 'formatters': {'myformatter': {'datefmt': '%Y-%m-%d %H:%M:%S %z', 'format': '[%(asctime)s] [%(levelname)s] %(message)s', 'class': 'logging.Formatter'}}, 'disable_existing_loggers': False, 'version': 1, 'loggers': {'': {'level': 'INFO', 'handlers': ['console', 'mail_admins'], 'propagate': False}, 'django': {'level': 'INFO', 'handlers': ['console', 'mail_admins'], 'propagate': False}}}, 'SECURE_HSTS_SECONDS': 0, '_wrapped': <Settings "squad.settings">, 'SECURE_HSTS_INCLUDE_SUBDOMAINS': False, 'DEBUG': False, 'DISALLOWED_USER_AGENTS': [], 'MIDDLEWARE': None, 'MESSAGE_STORAGE': 'django.contrib.messages.storage.fallback.FallbackStorage', 'APPEND_SLASH': True, 'USE_ETAGS': False, 'USE_X_FORWARDED_HOST': True, 'AUTH_USER_MODEL': 'auth.User', 'MIDDLEWARE_CLASSES': ['django.middleware.security.SecurityMiddleware', 'corsheaders.middleware.CorsMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.auth.middleware.SessionAuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'], 'X_FRAME_OPTIONS': 'SAMEORIGIN', 'STATIC_ROOT': '/home/squad/.local/share/squad/static', 'SESSION_SAVE_EVERY_REQUEST': False, 'INSTALLED_APPS': ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.humanize', 'corsheaders', 'whitenoise.runserver_nostatic', 'django.contrib.staticfiles', 'django_extensions', 'rest_framework', 'rest_framework.authtoken', 'rest_framework_filters', 'simple_history', 'django_filters', 'crispy_forms', 'squad.core', 'squad.api', 'squad.frontend', 'squad.ci']}

**Comment by chaws** [comment]
Hi @feine-moehre, did you get squad running alright after this?

**Comment by chaws** [comment]
I think this issue was solved. Please re-open if something similar happen again.
