### ISSUE TITLE
How to get case log from squad?

### ISSUE THREAD

**Issue by atline** [Linaro/squad#539]
See this: 

<img width="886" alt="Capture111" src="https://user-images.githubusercontent.com/3738458/58453455-cd662880-814d-11e9-8d36-26a4a3ea32d8.PNG">

How to get the failure case log by directly click the `red fail link` in `All test results`?

**Comment by atline** [comment]
Or any other way I can get the error cases' log directly, not just back to lava, search again?

**Comment by atline** [comment]
Also I see this, https://qa-reports.linaro.org/lkft/linaro-hikey-stable-rc-4.4-oe/tests/kselftest/bpf_test_align, maybe I can also click the `i` & click the link in it to visit my own defined log server?

But how can I make my project look like above url?

Or, any other suggestion I can quick get the exact error log for one case?

**Comment by atline** [comment]
I see this:

    <a href='#' data-toggle="modal" data-target="#info_modal" data-info="{{ result.info }}"><span data-toggle="tooltip" data-placement="right" title="{{ _('Show info') }}" class='fa fa-info-circle'></span></a>

And also:

```
<!-- Modal HTML -->
<div id="info_modal" class="modal fade" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ _('Test Info') }}</h4>
      </div>
      <div class="modal-body">
        <div id="test_description" style="display: none;">
          <p><strong>{{ _('Test description:') }}</strong></p>
          <div id="test_description_inner">
          </div>
        </div>
        <div id="test_reproduce" style="display: none;">
          <p><strong>{{ _('How to reproduce:') }}</strong></p>
          <div id="test_reproduce_inner">
          </div>
        </div>
        <div id="test_log" style="display: none;">
          <p><strong>{{ _('Test log:') }}</strong></p>
          <div id="test_log_inner">
            <pre></pre>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="modalClosed()">{{ _('Close') }}</button>
      </div>
    </div>
  </div>
</div>
```

How can I possible to enable `Show info`, then enable log show here for lava?

**Comment by mwasilew** [comment]
To get the log for single test you need to extract it from full log somehow. It's not that easy in LAVA, however possible. You would need to tell LAVA where START and STOP markers for test case are. Than LAVA associates this part of log with the test and SQUAD can retrieve that information. Here is some LAVA docs about that: https://master.lavasoftware.org/static/docs/v2/results-intro.html#accessing-associated-sections-of-test-job-logs

Full test job log is usually available from the test run page. With the link you gave it's (latest one): https://qa-reports.linaro.org/lkft/linaro-hikey-stable-rc-4.4-oe/build/4.4.181-rc1-hikey-20190520-442/testrun/736220/log
But I guess that's not very helpful as you have to dig through the log again.

This can also be done with plugin, like in case of CTS. Please check here: https://staging-qa-reports.linaro.org/android-lkft/android-8.1-tracking/build/53/testrun/1898185/suite/cts-lkft-armeabi-v7a$armeabi-v7a.CtsBionicTestCases/tests/
Here are plugin sources: https://github.com/Linaro/squadplugins/

I checked the code and I think we don't extract test log from LAVA natively even if it's there. So I'll change the title of this report and try to fix it. At the time the code was written LAVA didn't even support retrieving part of the log.

Lastly you're 100% correct that the UI isn't great. It could be much more intuitive.

**Comment by mwasilew** [comment]
I think I have a patch ready to fix this. This is how it's going to look like in the UI. Do you think the logs should be cleaned and only limited to 'target'? 
![lava_logs](https://user-images.githubusercontent.com/618901/58955420-d8dfd200-8793-11e9-99f2-d0ac35a6ac59.png)

**Comment by atline** [comment]
@mwasilew  It's great.

**Comment by atline** [comment]
Hi, @mwasilew 

Again me, sorry as I still have some question.

Your new changes maybe great, but it seems just parse the log print in lava web. But if the log run by tools did not print in lava, your changes still cannot meet the requirement.

Thus, we may still need to use the plugins here: https://github.com/Linaro/squadplugins/tree/master

For the above 2 plugins, I have tested it successfully with "tradefed" which used for android, but for "ltp", I failed. 

For "tradefed", I will use next to enable the log, it's ok:

        # Upload test log and result files to artifactorial.
        - cp -r ./${TEST_PATH}/results ./output/ || true
        - cp -r ./${TEST_PATH}/logs ./output/ || true
        # Include logs dumped from TF shell 'd l' command.
        - if ls /tmp/tradefed*; then cp -r /tmp/tradefed* ./output || true; fi
        - cp -r ./${TEST_PATH}/results ./output/ || true
        - ATTACHMENT="${TEST_PATH}-$(date +%Y%m%d-%H%M)-${BUILD}.tar.xz"
        - tar caf ${ATTACHMENT} ./output
        - curl -F "file=@${ATTACHMENT}" ${URL}
        - lava-test-reference "test-attachment" --result "pass" --reference "${URL}${ATTACHMENT}"

But, as in here: https://github.com/Linaro/squadplugins/tree/master/test, I even did not find a sample tar package for ltp, so I still cannot make my ltp work with failure log shown on squad.

So, can you give me a help how I can enable LTP log shown on squad with the plugin? E.g.

* what should I do in job definition?
* the archive also tar.xz?
* what files should be included in tar.xz?
* and what's the format of the files?

I see this https://github.com/Linaro/squadplugins/blob/master/test/test_ltp.py,

It said the format is:

```
test_1: some log 1
test_1: some log 2
test_1: some log 3
test_3: some log 1
test_3: some log 2
test_3: some log 3

```

But my real ltp log is something like next, which also confuse me.
Do we have any document for this at https://squad.readthedocs.io/en/latest/, or I miss some document?

```
<<<test_start>>>
tag=TGE-LV-MSS-MMC-0001 stime=1493227615
cmdline="emmc_01.sh buswidth8 $EMMC"
contacts=""
analysis=exit
<<<test_output>>>
+ RC=0
+ '[' 2 = 2 ']'
+ mmc=mmc2
+ '[' '!' -e /sys/kernel/debug/mmc2/ios ']'
+ setup
+ export TST_TOTAL=2
+ TST_TOTAL=2
+ export TCID=setup
+ TCID=setup
+ export TST_COUNT=0
+ TST_COUNT=0
+ trap cleanup 0
+ RC=0
++ mount
++ grep debugfs
++ wc -l
+ '[' 1 -eq 0 ']'
+ return 0
+ case "$1" in
+ test02
+ TCID=EMMC-02
+ TST_COUNT=2
+ RC=0
+ tst_resm TINFO 'EMMC-02: will check eMMC bus width is 8 bits'
EMMC-02     0  TINFO  :  EMMC-02: will check eMMC bus width is 8 bits
++ cat /sys/kernel/debug/mmc2/ios
++ grep 'bus width'
++ awk '{print $4}'
++ cut -c 2-
+ buswidth=8
+ '[' 8 -eq 8 ']'
+ return 0
+ cleanup
+ RC=0
+ return 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=1 cstime=2
<<<test_end>>>
<<<test_start>>>
tag=TGE-LV-MSS-MMC-0002 stime=1493227615
cmdline="emmc_01.sh clk $EMMC"
contacts=""
analysis=exit
<<<test_output>>>
+ RC=0
+ '[' 2 = 2 ']'
+ mmc=mmc2
+ '[' '!' -e /sys/kernel/debug/mmc2/ios ']'
+ setup
+ export TST_TOTAL=2
+ TST_TOTAL=2
+ export TCID=setup
+ TCID=setup
+ export TST_COUNT=0
+ TST_COUNT=0
+ trap cleanup 0
+ RC=0
++ mount
++ grep debugfs
++ wc -l
+ '[' 1 -eq 0 ']'
+ return 0
+ case "$1" in
+ test01
+ TCID=EMMC-01
+ TST_COUNT=1
+ RC=0
+ tst_resm TINFO 'EMMC-01: will test eMMC clock'
EMMC-01     0  TINFO  :  EMMC-01: will test eMMC clock
++ cat /sys/kernel/debug/mmc2/ios
++ grep '^clock'
++ awk '{print $2}'
+ clock=52000000
+ '[' 52000000 -eq 52000000 ']'
+ return 0
+ cleanup
+ RC=0
+ return 0
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=1 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=TGE-LV-MSS-MMC-0003 stime=1493227615
cmdline="emmc_kpi.sh read ${MMC_PATH} 27"
```

**Comment by mwasilew** [comment]
LTP plugin assumes you use this test definition: https://github.com/Linaro/test-definitions/tree/master/automated/linux/ltp. If you use sth else and store LTP logs to files you need to write your own plugin. LTP plugin from linaro-squad-plugins filters out LAVA 'target' level messages that match the pattern "test_name: some log line". That's all it does. You can see examples here:
https://qa-reports.linaro.org/lkft/linux-next-oe/build/next-20190607/testrun/763559/suite/ltp-syscalls-tests/tests/

For clarity, let's keep this ticket to cover collecting logs that LAVA maps in it's test results. If you need a different behaviour in LTP plugin or a new LTP plugin, let's discuss it in the plugins project here: https://github.com/Linaro/squadplugins/

**Comment by atline** [comment]
Clear, thanks, @mwasilew
