### ISSUE TITLE
Where to see the django log if submit job to lava failure?

### ISSUE THREAD

**Issue by atline** [Linaro/squad#546]
As a admin, I can not see any django log if squad for any reason fail to submit job to lava, where to find any log on server?

**Comment by mwasilew** [comment]
Can you see error message in the TestJob object itself? It should be stored there.

**Comment by atline** [comment]
You mean next diagram?

<img width="873" alt="111" src="https://user-images.githubusercontent.com/3738458/59170545-c2f65680-8b71-11e9-8cf9-5c2ac3bd61a2.PNG">

It shows "Not submitted", I struggle for several days, but still can not make it work, any evidence you can glimpse from above diagram? Please help, thanks.
