### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by keveryang** [Linaro/squad#554]
This happened after the first time running command './manage.py migrate' and './manage.py addsuperuser':

  Applying sessions.0001_initial... OK
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f8eeef8ac80>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f8eeef8ac80>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by chaws** [comment]
Hi @keveryang , does that happen every time you run `./manage.py migrate`? How is your set up?

**Comment by keveryang** [comment]
My Host is Debian 9.5(stretch), and here is the packages I have install:
sudo apt install libyaml-dev
sudo apt install python3-pip
sudo pip3 install --upgrade jinja2
sudo pip3 install -r requirements-dev.txt

It does not happen again when I run './manage.py migrate', maybe because all the migrations has been done:
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, ci, contenttypes, core, sessions
Running migrations:
  No migrations to apply.

**Comment by chaws** [comment]
This is a bug in Python < 3.6: https://bugs.python.org/issue29519

I've seen that happening other times, specially at the end of tasks, but that didn't mess up with the task itself. I guess we'll have to specify the minimal version of Python to be 3.6+

Thanks for reporting, @keveryang
