### ISSUE TITLE
Build compare not useful to LKFT

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#566]
I tried the new build compare feature today. Thanks!

Here's what it looks like: https://qa-reports.linaro.org/_/comparebuilds/?project=lkft/linux-stable-rc-5.1-oe&baseline=v5.1.17-137-gde182b90f76d&target=v5.1.17

I notice two things. First, well, there are 92 pages of results. Second is, most results consist of NA vs PASS. 

How could this be improved? Perhaps some filters to control the comparison. I'd like to be able to see a comparison of things that went from pass to fail, or fail to pass, for example.

**Comment by chaws** [comment]
@danrue that always got me thinking. At first, I think I can add an option that does something similar to art-reports (and to what you commented): show only differences. For now, test results diff are only in notifications, but I think it'll be useful in the front-end as well.

What do you think?

Browsing throughout the 92 pages, I think most of them will disappear when "diff-mode" is on.

**Comment by danrue** [comment]
Hi @chaws! diff mode would help, especially if it let you be particular about which transitions you care to see. Even with diff mode, there may be too many pages of results, so we may want to discard any diffs that only consist of going to or from N/A, for example.

On an unrelated note, is there any way to use this to compare builds across projects? It's a use-case we have, and which I do via the API periodically. Looking at the url parameters, it seems not possible, but I know the back end and API support it. Not sure how you'd support it in the UI though.

Thanks again,
Dan

**Comment by chaws** [comment]
@danrue 

> Hi @chaws! diff mode would help, especially if it let you be particular about which transitions you care to see. Even with diff mode, there may be too many pages of results, so we may want to discard any diffs that only consist of going to or from N/A, for example.

I like the "transitions" idea! After I talked to @mwasilew , we came up with a matrix of transitions that allows multiple filtering choices:

### Display selected transitions
| from/to | pass                   | fail                   | xfail                  | skip                   | n/a                    |
|:-------:|------------------------|------------------------|------------------------|------------------------|------------------------|
| pass    | -                      | <ul><li>[x] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> |
| fail    | <ul><li>[x] </li></ul> | -                      | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> |
| xfail   | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | -                      | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> |
| skip    | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | -                      | <ul><li>[ ] </li></ul> |
| n/a     | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | -                      |

Initially all non-differing results would be hidden. Results that are differing would go through this matrix and only the selected transitions would be displayed. Also, *pass-to-fail* and *fail-to-pass* transitions are marked as default. What are your thoughts about this?

> On an unrelated note, is there any way to use this to compare builds across projects? It's a use-case we have, and which I do via the API periodically. Looking at the url parameters, it seems not possible, but I know the back end and API support it. Not sure how you'd support it in the UI though.

There's a way of doing it which is at https://qa-reports.linaro.org/_/compare/. You can select two or more projects. The comparison objects are hard-coded as the most recent build of each selected project. If you needed to specify a different build from a specific project, then it's not in the UI :)

**Comment by mwasilew** [comment]
@chaws maybe we can add build selection to this view?

**Comment by chaws** [comment]
@mwasilew Makes sense. As projects get selected, a build selector (as in "compare-builds") would show up, allowing a user to enter that project's build version. What do you think?

**Comment by mwasilew** [comment]
Sounds good. Should be autocompleted (XHR) for easier operations.

**Comment by chaws** [comment]
@mwasilew , @danrue check this PR regarding project comparison: https://github.com/Linaro/squad/pull/569
