### ISSUE TITLE
Plugin to parse LAVA logs to find kernel issues

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#592]
We would like to be able to catch kernel panics, oopses, and warnings that may occur during LKFT runs. Each of these things should produce a "pass" or "fail" test result.

For example, we could have a dictionary like the following:
```py
kernel_tests = {
  'kernel_panic': r'',
  'kernel_oops': r'',
}
```

For each of these items, the regular expression will be run against the LAVA log and a test result will be produced.

Some regular expressions can already be found in LAVA @ https://git.lavasoftware.org/lava/lava/blob/master/lava_common/constants.py#L93-99

LAVA's implementation is not sufficient because it only runs against the boot portion of the job. LKFT would like to parse the entire kernel log for such errors.

I'm not sure how test names should be produced. It should be unique per job, but not per build.

cc @mrchapp @mattface @nareshkamboju

**Comment by mwasilew** [comment]
It's the same request as in squadplugins: https://github.com/Linaro/squadplugins/issues/3

**Comment by danrue** [comment]
@chaws pointed out https://github.com/Linaro/squad/blob/master/squad/plugins/linux_log_parser.py, which seems to already do exactly what I proposed in this issue. I've enabled it on https://qa-reports.linaro.org/lkft/linux-next-oe-sanity/ and https://qa-reports.linaro.org/lkft/linux-next-oe/ and will roll it out to the rest of the LKFT branches if it works as expected.

**Comment by danrue** [comment]
This isn't quite right.

![image](https://user-images.githubusercontent.com/409011/64352753-2ef62880-cfc2-11e9-905b-c17da9e8481b.png)

In LKFT's case, we run about 20 test jobs per environment, but we only get one check-oops result per environment. It should be one per job.

https://qa-reports.linaro.org/lkft/linux-next-oe/build/next-20190904/#!?details=47906

**Comment by mwasilew** [comment]
After a chat with @danrue we agreed that the plugin should report panics/oopses/warnings for each LAVA test job (which translatest to TestRun). It will take a metadata key (to be agreed) and add the key to the test name. So for example for ltp-syscalls test job it will produce:
* ltp-syscalls-panics
* ltp-syscalls-oopses
* ltp-syscalls-warnings
test cases. These test cases will be added to test run whenever the plugin is enabled on the project. Test cases will be 'passed' when there are no panics/oopses/warnings and 'failed' otherwise. It would also be nice to have ability to overwrite the default regexes for the plugin. I guess this can be done with project settings field.

**Comment by danrue** [comment]
By the way, I think this alternative implementation being proposed in kernelci is interesting: https://github.com/kernelci/kernelci-core/pull/177

**Comment by mwasilew** [comment]
@danrue you can do that already now. It doesn't require any plugin in SQUAD. I think this might be a good start, but plugin can do a bit more (for example attach log snippet to the test report). Up to you which way to go.

**Comment by danrue** [comment]
Here is the problem. Squad's implementation will not be able to distinguish between build-time issues and test-time issues.

Some tests induce kernel warnings and such intentionally, which will create noise in the data.

Using kernelci's approach isn't very efficient; we've hit filesystem size problems when having too many tests defined in a job (due to one test-definitions clone per test definition). We'd want to run it after boot always, and then sometimes after tests.

So, I think we should proceed as discussed in SQUAD because it'll be an immediate improvement. We'll have to mark the test jobs that always have a fail as known issues, but this will still help us catch other issues.

**Comment by chaws** [comment]
@danrue perhaps after we clear https://github.com/Linaro/squad/pull/614 we can sort out a way of telling squad not to consider such tests as a fail, like we have today for known issues
