### ISSUE TITLE
Use LAVA's get results yaml

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#604]
I noticed that we're implementing something that seems to be already implemented in LAVA. The method I'm referring to is https://github.com/Linaro/squad/blob/master/squad/ci/backend/lava.py#L290, and the LAVA function that seems to do the same thing is here https://validation.linaro.org/api/help/#results.get_testjob_results_yaml

@mwasilew any particular reason why not to use LAVA's? This would speed up fetching things by a lot, specially in cases where there's multiple suites.

**Comment by chaws** [comment]
Ah, saw why: https://github.com/Linaro/squad/commit/39b7a6d8dc2170b2b1f2346b52bd29d2957f4457

**Comment by mwasilew** [comment]
Loading a huge YAML to memory isn't a great idea. In case of CTS there can be 500k test results which creates a huge YAML file. Instead we're fetching in chunks to prevent timeouts and crashes. I don't think changing that would be a big improvement (in terms of time) and might cause issues with memory.

**Comment by chaws** [comment]
I think we're fetching results twice for tradefed enabled projects: 
https://github.com/Linaro/squadplugins/blob/master/tradefed/__init__.py#L129

**Comment by mwasilew** [comment]
Yep, I don't think there is any better way of finding a proper test in LAVA. If LAVA's REST API had filters...

**Comment by chaws** [comment]
Oh, I figured out that the tradefed is downloading artifacts of that testjob. On a side note, I think we can improve tradefed's performance significantly by gathering all `test_definition['name']` and scan the testjob results for attachments only once.

**Comment by stevanradakovic** [comment]
> Yep, I don't think there is any better way of finding a proper test in LAVA. If LAVA's REST API had filters...

https://git.lavasoftware.org/lava/lava/issues/333 if I'm not missing a point here.
I can bump up the priority if you want, right now milestone is set to .12

**Comment by mwasilew** [comment]
@stevanradakovic no need to prioritize this. We lived with this issue for some time and 2 more months won't make a big difference. The main issue with performance is not related to retrieving LAVA results.

**Comment by mwasilew** [comment]
https://git.lavasoftware.org/mwasilew/lava/commit/b0d2baa023e0f14be821dd17f25bdffb102ffc6c
Not merged yet and it's a pretty old branch. I guess once REST API for results is implemented we can come back to this ticket.

**Comment by chaws** [comment]
Got it

**Comment by stevanradakovic** [comment]
> Yesterday I also tried using custom queries (https://lkft.validation.linaro.org/api/help/#results.make_custom_query), but didn't actually work :(
> 
> In some cases I'm able to retrieve tests, but I found not way to filter tests by job_id

Can you give me an example or a link to a query that you tried to create. This should be possible to do.

**Comment by chaws** [comment]
@stevanradakovic , it was something like that:

`tests = lava.proxy.results.make_custom_query('testcase', 'testsuite__job__sub_id__exact__948691')`

But that got me a 403

**Comment by stevanradakovic** [comment]
the conditions for testcase can follow testjob relation directly so correct way to do it would be 'testjob__sub_id__exact__948691'... unfortunately, the conditions do not support id fields (here's the list of supported ones https://git.lavasoftware.org/lava/lava/blob/master/lava_results_app/models.py#L1155)
But you got a 403 that is a whole other issue. Either an incorrectly thrown error or some authorization problem.

**Comment by mwasilew** [comment]
I think this will be fixed by #697

**Comment by chaws** [comment]
That got me thinking, what about loading huge test sets in memory? I would guess LAVA returns data in a paginated fashion. We'll have to test it then

**Comment by mwasilew** [comment]
Yes, it's paginated. The implementation takes care of pagination on SQUAD side.

**Comment by mwasilew** [comment]
#697 is merged. I propose to close this ticket.
