### ISSUE TITLE
API filters don't work correctly

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#606]
API filters for Test object don't work. An example is this URL:
https://qa-reports.linaro.org/api/tests/?test_run__build__project__slug=linux-mainline-oe&test_run__environement__slug=x86&test_run__build_version=v5.3-13285-gbb48a5913592

It returns Test object with ID=126150. Going into shell gives following results:
```
>>> from squad.core.models import *
>>> t = Test.objects.get(pk=126150)
>>> t.test_run.environment
<Environment: hi6220-hikey - arm64>
>>> t.test_run.build.version
'v4.12-rc6-102-ga38371c'
>>> t.test_run.build.project
<Project: lkft/linux-mainline-oe>
```
So only project filter is correct. Both environment and version are wrong.

**Comment by chaws** [comment]
I've run this on the db directly, and I found out why it didn't work:

- `test_run__build_version` looks for a attribute in test_run called `build_version`, this definitely was supposed to have double `_` after "build"
- `test_run__environement` has a typo "environement" instead of "environment".

So, because that query is being managed by django filters and django rest framework, it didn't report these errors anywhere. Should we make it report such errors?

**Comment by chaws** [comment]
https://stackoverflow.com/questions/22178266/django-rest-framework-raise-error-when-extra-fields-are-present-on-post

I'll tackle that next week

**Comment by mwasilew** [comment]
By default djangorestframework-filters ignores extra keywords. I'm not sure there is a setting to prevent that. It would be nice if it reported like filter() function in the shell:
```
>>> tests = Test.objects.filter(test_run__build__project__slug="linux-mainline-oe", test_run__build__version="v5.3-13285-gbb48a5913592", test_run__environement__slug="x15", test_run__build__project__group__slug="lkft")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1243, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: environement
```

**Comment by chaws** [comment]
Maybe having a generic validator that gets the queryset originated from the request parameters before doing the actual query would be nice

**Comment by mwasilew** [comment]
I don't think it's easy or worth to fix. Closing.
