### ISSUE TITLE
Is this LAVA issue fixed?

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#624]
Is this fixed in LAVA? https://github.com/Linaro/squad/blob/3efe7a11b26efcce9f41a69d2c7616264db57c0f/squad/ci/backend/lava.py#L458

It's been two years since that got in: https://github.com/Linaro/squad/commit/50f694d965e5e19e46ae667ce99ff2e884c8d707

**Comment by mwasilew** [comment]
Good question. I will ask LAVA guys.

**Comment by mwasilew** [comment]
This should be fixed. You can remove countdown and then test in staging.

**Comment by chaws** [comment]
Thanks for checking.
I'll wait https://github.com/Linaro/squad/pull/626 to be merged first so we try one thing at a time.
