### ISSUE TITLE
LKFT: kernel warning did not catch by Linux-log-parser

### ISSUE THREAD

**Issue by nareshkamboju** [Linaro/squad#633]
linux-log-parser is catching kernel panic and warning which is really
helpful feature.

For some reason the below kernel warning did not catch by Linux-log-parser.
I request to enhance it to catch these kind of warnings from boot log.

FYI, This kernel warning from boot console occurring on all
stable-rc-4.19 and stable-rc-4.14 on arm64 boards.

Kernel warning log from boot console,

[    0.077226] =============================
[    0.077274] WARNING: suspicious RCU usage
[    0.077325] 4.14.156-rc1 #1 Not tainted
[    0.077371] -----------------------------
[    0.077420] /usr/src/kernel/include/linux/radix-tree.h:238
suspicious rcu_dereference_check() usage!

ref:
1)
https://qa-reports.linaro.org/lkft/linux-stable-rc-4.14-oe/build/v4.14.155-123-gd40687ee9ee0/testrun/1019828/
https://lkft.validation.linaro.org/scheduler/job/1019828#L1000

2)
https://lkft.validation.linaro.org/scheduler/job/1019767#L595
https://qa-reports.linaro.org/lkft/linux-stable-rc-4.14-oe/build/v4.14.155-123-gd40687ee9ee0/testrun/1019767/

**Comment by chaws** [comment]
I'm going to try this log with the improved version of the plug in

**Comment by chaws** [comment]
@nareshkamboju , testing these logs against the improved version (being reviewed) of log parser, the `WARNING: suspicious RCU usage` message is detected successfully. The downside is that the other lines aren't contained in the test log. I tried to make a pattern that finds that warning ending, but briefly looking into kernel code where this message appear, is seems that it'll change for every type of warning.

**Comment by danrue** [comment]
Please compare with kernelci's log parsing implementation, as they do the same thing.

**Comment by chaws** [comment]
Hi Dan, is kernelci parsing build or boot logs? I was only able to find build log parsing: https://github.com/kernelci/kernelci-backend/blob/master/app/utils/log_parser.py

Briefly greping for 'panic', 'WARNING:' or 'Oops' didn't find anything in kernelci-{core,backend,frontend}.

**Comment by danrue** [comment]
I know of two places. The one you mentioned, and then I was also thinking of this one: https://github.com/kernelci/kernelci-core/pull/177/files - I guess that second one is out of squad's ability to implement since it requires calling 'dmesg' on target.

**Comment by chaws** [comment]
Just saw that PR, and you're right that's being done within a test in LAVA. I was wondering if their solution also captures kernel panic

**Comment by chaws** [comment]
Closing in favor of: https://github.com/Linaro/squad/issues/658

Apparently it's not 100% working
