### ISSUE TITLE
API feature: batch retrieve tests and metrics for a build

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#634]
Sometimes, API clients need to retrieve all data related to a particular build in squad. Currently it costs at least two API requests per testrun, a few requests per build, and one request per 1000 testruns (if a non-default limit is specified).

As an example, consider the use-case of retrieving all tests results for the following build, the subsequent API calls are required (at least):
- https://qa-reports.linaro.org/api/builds/26055
  - https://qa-reports.linaro.org/api/builds/26055/status/
  - https://qa-reports.linaro.org/api/builds/26055/metadata/
  - https://qa-reports.linaro.org/api/builds/26055/testruns/?limit=1000
    - (191x) https://qa-reports.linaro.org/api/testruns/1983822/tests_file/
    - (191x) https://qa-reports.linaro.org/api/testruns/1983822/metrics_file/

In total, this is 386 API requests to retrieve all test results and metric results for a single LKFT build.

To get an idea of timing, I ran the following:
```
drue@xps:~$ time for url in $(curl 'https://gist.githubusercontent.com/danrue/34cac389b4db0d0f9aded911d9f4c396/raw/f2ab410f996a05559d6bfbcbac0c58a3e867a9de/gistfile1.txt'); do echo $url; curl $url; done
...
real    1m41.467s
user    0m12.476s
sys     0m3.594s
```

For a single build, this isn't unreasonable, but consider a project with many more test runs, or consider if you wanted to retrieve say, 10 builds and 10 branches - then you're looking at runtime measured in hours, with heavy load on SQUAD's API.

Please consider providing a way to retrieve all tests results and metrics results for a particular build, to reduce the number of API requests required.

**Comment by amrohassaan** [comment]
@danrue thanks for the request and the example. I talked with @mwasilew  today about this. I will pick this @mwasilew.
