### ISSUE TITLE
Show failed test suites

### ISSUE THREAD

**Issue by mrchapp** [Linaro/squad#655]
In the build view, e.g. https://qa-reports.linaro.org/lkft/linux-stable-rc-5.5-oe/build/v5.5.4-81-g8aa3a43b129c/, it would be great if we could see the test suites that have failures in them. That used to be the case before all environments got grouped together.

I'm thinking a button to show those failed test suites in all environments would be good (with those failed test suites shown by default when loading that page), and adding such a button would go very well with a [Collapse All]/[Expand All] button too.

So, 1) show test suites that have failures by default, 2) maybe add some buttons [Show Failures], [Collapse All]/[Expand All].

Expected failures should not matter for determining if a test suite had failures. I.e. that if `kvm-unit-tests` had 0 fails and 5 xfails, then it should not be shown; on the other hand, if perf has 5 xfails and 1 fail, then it should be shown.

**Comment by chaws** [comment]
Hi @mrchapp , you can go back to that old view just by selecting from that dropdown next to `Test Results` label: https://qa-reports.linaro.org/lkft/linux-stable-rc-5.5-oe/build/v5.5.4-81-g8aa3a43b129c/?results_layout=table#!#test-results

For the other test results layout (by suites / by environments), suite results are sorted by failures first, then alphabetically. Does that help you?

Regarding a `collapse/expand all` option, that's a great idea.

**Comment by mrchapp** [comment]
@chaws, I like the two new groupings. What I'm missing is seeing the failures at first sight.

In the build I linked to ("by environments"), in the Dragonboard 410c results I'd like to see the testsuites `kselftest` and `perf` only; in Hikey, nothing; in i386, `kselftest`, `perf`, and `spectre-meltdown-checker-test`; and so on for the other boards.

This is particularly useful for that view, "by environments", and "suites x environment". Not sure how useful it is for "by suites", but that kind of filtering can be helpful as a default.

**Comment by chaws** [comment]
@mrchapp hummm got it!

Perhaps when it's in `by suites`, ltp-syscalls-tests would show only the environment `nxp-ls2088`, and for suites that had no failures, they would be hidden when such `failures only` option is enabled. 

What do you think?
