### ISSUE TITLE
change LAVA interface to use REST API

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#659]
LAVA REST API is functional and all features that SQUAD uses should be available. Let's try to drop all XML-RPC calls and replace them with REST.

**Comment by chaws** [comment]
:fearful:

**Comment by mwasilew** [comment]
Depends on https://git.lavasoftware.org/lava/lava/-/issues/404

**Comment by mwasilew** [comment]
I found another issue in LAVA API. Fixed here: https://git.lavasoftware.org/lava/lava/-/merge_requests/1143
