### ISSUE TITLE
Add metrics top-level endpoint identical to Tests

### ISSUE THREAD

**Issue by amrohassaan** [Linaro/squad#673]
For efficiency in extracting and reporting, metrics should have a dedicated top-level endpoint similar to Tests. This became very evident when using the client. One shouldn't have to query Testruns to get to metrics. This will help maintaining abstract design and light weight on client as well.

**Comment by mwasilew** [comment]
Metrics have stricter requirements for access control. Please keep that in mind when writing the code.
