### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by mr-sour** [Linaro/squad#680]
Lava has official images that are versioned and released each month. It would be great if squad also had a matching official image to along with that. I currently have to build and manage this image myself which is kind of a hassle when I goto update as I have to build the whole thing again and keep track of my own image.

https://hub.docker.com/u/linaro

https://git.lavasoftware.org/lava/lava/container_registry

**Comment by chaws** [comment]
Hi @mr-sour , I'm currently working on migrating our deployment to containers, so I'll probably have an official docker image in the following weeks here: https://hub.docker.com/r/qareports/squad/

We've tried taking https://hub.docker.com/u/squad/ but that's already taken :(

**Comment by chaws** [comment]
Just a follow up: the official docker image for SQUAD will be hosted at https://hub.docker.com/repository/docker/squadproject/squad

I'll keep the image version in sync with squad version in pypi, also I'll sync the dockerhub with this repo.

**Comment by chaws** [comment]
@mr-sour official SQUAD images will be hosted at https://hub.docker.com/r/squadproject/squad. Feedbacks are welcome!

I'm closing this now, thanks for opening this ticket
