### ISSUE TITLE
Logs button

### ISSUE THREAD

**Issue by mrchapp** [Linaro/squad#690]
Once we get to this view:
  https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.7-rc1-24-g8632e9b5645b/testrun/1363280/suite/kselftest/tests/
it would be very helpful to go straight to see the logs of a failed test, straight to the LAVA log where the failure occurred.

(For some reason the info shown with "Show info" is not very informative.)

**Comment by mwasilew** [comment]
@mrchapp 'show info' is the exact line lava gives us. I guess what you're asking is linking to this file: https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.7-rc1-24-g8632e9b5645b/testrun/1363280/log with anchor at the line pointed to by test case. Is this correct?

**Comment by mrchapp** [comment]
Exactly. I think even without the anchor it would already be an improvement. Currently, you need to click on the job number in the path (of course, you need to know that) and then on the `job_url` link of the metadata.

See [this report](https://lore.kernel.org/lkml/CACT4Y+bi9jFKR5vHY37-RoojUiVkX6Pu69X-2F+ibo6pSCA==Q@mail.gmail.com/) from the wild:

> I can't find any actual test failure logs in the UI. I've got to this page:
> https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.7-rc1-24-g8632e9b5645b/testrun/1363280/suite/kselftest/tests/
> which seem to contain failed tests on mainline. But I still can't find
> the actual test failure logs
