### ISSUE TITLE
metrics chart page is too slow

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#694]

**Comment by leeoniya** [comment]
@chaws https://github.com/leeoniya/uPlot

**Comment by chaws** [comment]
Hey @leeoniya Thanks for the tips.

I opened this issue after I debugged out app and found out the the backend is super slow rendering the HTML page. It's something shady in Django request middlleware I haven't figured yet. The chart.js lib is not our bottleneck. I really appreciate your suggestion though, will bring it up in our team sync in the future :)

**Comment by leeoniya** [comment]
heh, sure :)

**Comment by stevanradakovic** [comment]
https://github.com/Linaro/squad/pull/825 hopefully a fix

**Comment by chaws** [comment]
People don't seem to visit metrics page very much. Will close this for now. If you're reading this and still thinks metrics page is too slow, please leave comments
