### ISSUE TITLE
api returns urls instead of ids for id fields

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#704]
A lot of the data returned from the squad api is coming back as full URLs to data instead of as regular IDs. Is there a reason for this?

**Comment by mwasilew** [comment]
Easier navigation? Is this a problem?

**Comment by jscook2345** [comment]
I'm just trying to understand things. Opening an issue for me is just like answering a question. I like issues because I can link to them and they retain history.

How does providing a URL over an ID provide easier navigation to libraries that consume the API?

**Comment by jscook2345** [comment]
Here is an example of me mistaking a URL for an ID field.

```
Traceback (most recent call last):
  File "report.py", line 54, in <module>
    run = Squad().testruns(id=j.testrun).pop(j.testrun)
KeyError: 'https://qa-reports.linaro.org/api/testruns/2553969/'
```

I assumed the `testrun` field of the `TestJob` object was an ID, when in reality it is a URL.

**Comment by mwasilew** [comment]
Right, this might be an issue. IIRC I had to work around that in squad-config. The change will break current API so we'll need to introduce new version. Here is squad-config code for this part:
https://github.com/Linaro/squad/blob/master/scripts/squad-config#L174
I'm not sure it still works. We made a few changes after it was completed.

**Comment by mwasilew** [comment]
@terceiro do you remember why we used URLs instead of IDs? Will there be any problem with using IDs now?

**Comment by terceiro** [comment]
the API is designed to be auto-discoverable. if you use URL's as reference to related objects, clients don't need to hardcode any knowledge about the API endpoints - you only need to know the URL of the API root

**Comment by chaws** [comment]
I guess standardizing all to URLs instead of IDs is the way to go then?

**Comment by mwasilew** [comment]
Right now we have both in most of the cases :) But I agree we should stick to one standard and let it be URLs.

**Comment by jscook2345** [comment]
Sounds good to me. Feel free to close this issue and open a pr instead. Please mention me (@jscook2345) on the pr so I know when it is completed. Thanks!

**Comment by chaws** [comment]
I'm reviving this thread next week, as I'm implementing methods to add objects via squad-client. I'm working on a patch for this already and will be sending one here as well to standardize all IDs to become URLs. I'll ping you @jscook2345
