### ISSUE TITLE
Expose previous build in build status

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#708]
I see that there is a status assigned to a build (ex: https://qa-reports.linaro.org/api/builds/35450/status/), but it does not list what the previous build was. I think that should be included.

**Comment by jscook2345** [comment]
@mwasilew @chaws I think this is a higher priority issue.

**Comment by mwasilew** [comment]
Thanks @jscook2345. I already started working on this. It requires a fair bit of changes to the models.

**Comment by danrue** [comment]
@mwasilew since we're implementing a linked list here... just in case it's possible, a "next build" field would also be helpful so that you could traverse builds in either direction (forward or backward).

**Comment by mwasilew** [comment]
@danrue I didn't think about that :) I guess it's possible. The problems start once you try to delete Build objects. But it's an issue for single and double link list. I'll think about that. Thanks!

**Comment by mwasilew** [comment]
@danrue this isn't a linked list (single or double). There is at least one use case that makes link list impossible. We have a test case that checks whether builds always use previous _finished_ build as a baseline. It can happen that finished build is followed by unfinished one. When 3rd build comes it has to have the same baseline as the already unfinished build:

build1 (finished)
build2 (unfinished) - baseline: build1
build3 (unfinished) - baseline: build1

Later build3 can switch baseline to build2 but at least for some time we have to allow for one-to-many relation for baseline. This excludes linked list.

**Comment by chaws** [comment]
@mwasilew in the use case you pointed, which build should be build1's next_build?

**Comment by mwasilew** [comment]
@chaws both build2 and build3. Any better idea?

**Comment by mwasilew** [comment]
@jscook2345 I might be reading your request incorrectly. Are you looking for the reference to the baseline (build that was used to calculate regressions and fixes) or the actual previous build (in whatever state it is)?

**Comment by jscook2345** [comment]
@mwasilew 

The baseline. I would use the previous build for looking over regressions and fixes as you say.
