### ISSUE TITLE
Duplicate fields for api/projects/ID/suites

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#711]
There are two fields for `Slug contains` in the filters list

ex: https://qa-reports.linaro.org/api/projects/6/suites/?limit=50

**Comment by mwasilew** [comment]
I guess it's just a rendering error in DRF. One is 'contains', the other 'icontains' (case insensitive). IMHO not worth fixing with custom templates. I'll try to check where the bug really comes from.

**Comment by mwasilew** [comment]
OK, found it in django-filter:
https://github.com/carltongibson/django-filter/blob/fbb67b6d8d8a8114c69c16b8eaba81cea68e839e/django_filters/conf.py#L32

**Comment by jscook2345** [comment]
Sounds good. Thanks!
