### ISSUE TITLE
testrun status endpoint not discoverable via the web view

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#712]
I found that there is a `/status/` available for the `testrun` endpoint in the `squad-client` code, but it is not shown in the web api anywhere.

https://qa-reports.linaro.org/api/testruns/2649235/status/

Note that if you visit here:

https://qa-reports.linaro.org/api/testruns/2649235/

There is no way to get to the status that I can see. The build  endpoint did have a way to discover the build status.

https://qa-reports.linaro.org/api/builds/36478/

See the `status` field in the above url.

**Comment by mwasilew** [comment]
@jscook2345 I checked it and indeed there is no way to discover testrun status. It's a nested endpoint and I see no way to include it in the object serialization. We're using the extension library that doesn't support it. At least I can't find the way of adding 'status' field. Would it be enough to include it in the docs and docstring? Docstring is rendered in the browsable API. Alternative is to replace drf-extensions with other library that supports announcing nested endpoints.

**Comment by jscook2345** [comment]
@mwasilew 

Can I see a preview of what you're describing? Any docs announcing the availability of that end point would be a great start I think.

**Comment by mwasilew** [comment]
@jscook2345 sth like the picture below
![squad_testrun_docstring](https://user-images.githubusercontent.com/618901/81811280-4b1c7300-951c-11ea-9dfa-d1bbd9529f69.png)

I'll push it on a branch as it makes sense to merge it anyway.

**Comment by jscook2345** [comment]
Looks great to me! Thanks @mwasilew !

**Comment by chaws** [comment]
@jscook2345 FYI I rolled that out yesterday https://qa-reports.linaro.org/api/testruns/

Thanks for reporting :)
