### ISSUE TITLE
Add annotation: "There was an error while editing annotation. Message: undefined"

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#718]
Just looked at my fresh results: https://qa-reports.linaro.org/pfalcon/zephyr-net/build/f95c349c/ , and saw an "Add annotation" button which invited to be pressed with blue background. So, I did, and typed "First run" in the dialog. After pressing "Save", there was a JS popup saying:

~~~
There was an error while editing annotation.
Message: undefined
~~~

![Screenshot at 2020-05-06 16-29-03](https://user-images.githubusercontent.com/500451/81182924-21f96100-8fb7-11ea-9826-83ce0b0b2944.png)

**Comment by chaws** [comment]
It was a permission issue. I gave @pfalcon the required permissions and now it should work.

Regarding the "undefined" message, that got fixed here: https://github.com/Linaro/squad/pull/730

I'm closing this ticket for now, please re-open if the error persists.

**Comment by pfalcon** [comment]
Confirming works for me, thanks for quick turnaround!
