### ISSUE TITLE
UI: Can't subscribe to project notifications from project, d'oh

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#723]
Steps to reproduce:

1. Be at the project page, e.g. https://qa-reports.linaro.org/pfalcon/zephyr-net/
2. Want to subscribe to project (email) notifications.
3. Seeing no obvious "bell" icon straight on the page itself, proceed to "Project settings" tab.
4. Wander endless to still find nothing.
5. Be perplexed, perhaps assume that SQUAD doesn't support notifications.
6. By a pure chance, go to a user Settings, and find "Subscriptions" tab there.

Don't get me wrong - such a tab, listing all subscriptions and allowing to unsubscribe from a particular one, definitely should be there. But the most obvious place to subscribe to a project is a project itself. The current subscription interface with that gigantic dropdown is rather unwieldy and probably even took more effort to code.

If this is acted upon, I really recommend to consider making the "subscribe" action easily accessible, based on the argument presented in https://lists.lavasoftware.org/pipermail/lava-users/2020-April/002380.html - that there would be a noticeable share of users who are interested to look at the test results in 2 cases: a) during initial project setup; b) when tests fail. To achieve b), they would need to subscribe to notifications, so that should be "at fingertips" action.

Specifically, I might suggest to include "Subscription" tab in Project settings, where all settings are collected, but also add a quick-access straight from the project page(s), which can be in the form of a tab heading or a graphic icon (a bell or similar). In both cases, it should lead to a page with additional subscription options and confirmation button, not lead to an immediate action with some "defaults".

Thanks.

**Comment by pfalcon** [comment]
And yeah, I'm actually keep hitting this issue again and again.

**Comment by mwasilew** [comment]
I totally agree, subscribe button will be a nice addition to the project page.

**Comment by pfalcon** [comment]
Thanks! It's really hard to complain when your bugs are looked into, and such quickly, but for history, there's a concern that the implemented and linked solution (#726) addresses the concern only partially: https://github.com/Linaro/squad/pull/726#issuecomment-627944793

**Comment by mwasilew** [comment]
@pfalcon you can have something 'quickly' or nothing for a pretty long time. IMHO former is better.

**Comment by pfalcon** [comment]
@mwasilew: I definitely agree, and appreciate it. And I'm actually not sure what's better strategy to show my appreciation - to keep silence of gratitude that something gets done at all, or strive to participate better, e.g. review the fixes which get done, and provide feedback, with full understanding that "good is the enemy of the best" and not everything is actionable right away.

**Comment by mwasilew** [comment]
We can keep this ticket open (need to reopen) or create a new one for changing notification level in the UI. It's up to you which option is better.

**Comment by pfalcon** [comment]
> We can keep this ticket open (need to reopen) or create a new one for changing notification level in the UI. It's up to you which option is better.

Thanks, it's very helpful to get a hint that it's ok for the project to treat such issues as not fully finished, and keep them in queue. Specific process wise, please let me wait and see the new feature in action, then submit a new ticket, if needed, and in relative priority to other things. Thanks!
