### ISSUE TITLE
UI: Build page: Switching among suites*envs/suites/envs views resets "failures only" checkbox

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#725]
Steps to reproduce:

1. Go to a page like https://qa-reports.linaro.org/pfalcon/zephyr-net/build/c6edfa09/
2. Uncheck "failures only" checkbox.
3. In the nearby dropdown, choose "by suites".
4. Watch that "failures only" checkbox was automatically switched to be set again, so you don't see any useful information that you expected, and need to do extra handwork again. This (re)setting happens on each view switch.

Expected behavior: on initial page open, "failures only" should be set, and afterwards, while switching views, the checkbox should preserve last value set by user.

**Comment by mwasilew** [comment]
Thanks @pfalcon, nice catch!

**Comment by chaws** [comment]
Closed in #743
