### ISSUE TITLE
Noticeable latency with fetching LAVA results (qa-reports.linaro.org)

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#733]
I find that there are (or can be) noticeable delays with fetching LAVA test results back into SQUAD for display, on the https://qa-reports.linaro.org deployment.

As it's largely an intuitive feeling, I'm creating this ticket to collect objective "evidence" over some time, to serve as an input to SQUAD maintainers whether there's something to improve.

**Comment by pfalcon** [comment]
A case:

https://lite.validation.linaro.org/scheduler/job/1036422 was submitted "52 minutes ago" and still not fetched, even once, according to https://qa-reports.linaro.org/pfalcon/zephyr-jerryscript/build/d483a5d3/testjobs/ (fetched result at the bottom is for previous batch of tests against the same build id (git revision)) :

![Screenshot at 2020-05-18 15-20-10](https://user-images.githubusercontent.com/500451/82212355-17c25580-991b-11ea-8ba0-5382f60abc8a.png)

**Comment by pfalcon** [comment]
Oops, posted this ticket, refreshed https://qa-reports.linaro.org/pfalcon/zephyr-jerryscript/build/d483a5d3/testjobs/, and all is fetched now. Thus fetching latency in this case was between 52 and 57 minutes.

**Comment by mwasilew** [comment]
I guess it's pretty good measurement. Default polling time is 1h. I wonder why we don't get ZMQ notifications about completed tasks. Let me follow up on that. Unless there is a huge queue (which is usually not the case) the delay between job completed and results retrieved should be withing couple of minutes (in theory). There may be cases when the task queue is pretty long. It might also be a side effect of AWS SQS service. It has some undesired properties blocking tasks in the queue. We have a plan to migrate back to RabbitMQ which behaves much better in this respect.

**Comment by mwasilew** [comment]
This should now be fixed after we moved to RabbitMQ and setup all workers as k8s pods.
