### ISSUE TITLE
Potential dependency conflicts between squad and django

### ISSUE THREAD

**Issue by NeolithEra** [Linaro/squad#737]
Hi, as shown in the following full dependency graph of **_squad_**, **_squad_** requires **_django >=2.2,<3.0_**, **_squad_** requires **_django-rest-framework >=3.9.2_** (**_django-rest-framework 3.11.0_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_django-rest-framework 3.11.0_** transitively introduces **_django >=1.11_**.

Obviously, there are multiple version constraints set for **_django_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_django 2.2.12_** (i.e., the newest version satisfying constraint **_>=2.2,<3.0_**) is the actually installed version.

Although the first found package version **_django 2.2.12_** just satisfies the later dependency constraint （**_django >=2.2,<3.0_**), such installed version is very close to the upper bound of the version constraint of django specified by **_django-rest-framework 3.11.0_**. 

Once **_django-rest-framework_** upgrades，its newest version will be installed, as **_squad_** does not specify the upper bound of version constraint for **_django-rest-framework_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_django-rest-framework_** version introduces a higher version of **_django_**, violating its another version constraint **_>=2.2,<3.0_**.

According to the release history of django-rest-framework, it habitually upgrates Django in its recent releases. For instance, django-rest-framework 3.11.0 upgrated Django’s constraint from *  to >1.1.1, and django-rest-framework next version upgrated Django’s constraint from >=1.11 to >2.2. 

As such, it is a warm warning of a potential dependency conflict issue for squad.

### Dependency tree
```
squad  - 1.12
| +- celery(install version:4.4.2 version range:*)
| +- coreapi(install version:2.3.3 version range:*)
| | +- coreschema(install version:0.0.4 version range:*)
| | | +- jinja2(install version:2.11.2 version range:*)
| | | | +- MarkupSafe(install version:2.0.0a1 version range:>=0.23)
| | +- itypes(install version:1.1.0 version range:*)
| | +- requests(install version:2.23.0 version range:*)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| | +- uritemplate(install version:3.0.1 version range:*)
| +- Django(install version:2.2.12 version range:>=2.2,<3.0)
| | +- pytz(install version:2019.3 version range:*)
| | +- sqlparse(install version:0.3.1 version range:*)
| +- django-cors-headers(install version:3.2.1 version range:*)
| +- django-simple-history(install version:2.8.0 version range:*)
| | +- six(install version:1.14.0 version range:*)
| +- djangorestframework(install version:3.11.0 version range:>=3.9.2)
| | +- django(install version:3.0.5 version range:>=1.11)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- djangorestframework-filters(install version:0.11.1 version range:>=1.0.0.dev0)
| | +- django-filter(install version:1.1.0 version range:<2,>=1.1)
| | +- djangorestframework(install version:3.11.0 version range:*)
| | | +- django(install version:3.0.5 version range:>=1.11)
| | | | +- asgiref (install version: version range:=3.2)
| | | | +- pytz(install version:2019.3 version range:*)
| | | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- django_crispy_forms(install version: version range:*)
| +- django_filter(install version: version range:>=2.0)
| +- drf-extensions(install version:0.6.0 version range:*)
| | +- djangorestframework(install version:3.11.0 version range:>=3.9.3)
| | | +- django(install version:3.0.5 version range:>=1.11)
| | | | +- asgiref (install version: version range:=3.2)
| | | | +- pytz(install version:2019.3 version range:*)
| | | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- gunicorn(install version:20.0.4 version range:*)
| | +- setuptools(install version:46.1.3 version range:>=3.0)
| +- Jinja2(install version:2.11.2 version range:*)
| | +- MarkupSafe(install version:2.0.0a1 version range:>=0.23)
| +- Markdown(install version:3.2.1 version range:*)
| | +- setuptools (install version:46.1.3 version range:>=36)
| +- msgpack(install version:1.0.0 version range:>=0.5.0)
| +- psycopg2(install version:2.8.5 version range:*)
| +- python_dateutil(install version: version range:*)
| +- PyYAML(install version:5.3.1 version range:>=5.1)
| +- pyzmq(install version:19.0.0 version range:*)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- sqlparse(install version:0.3.1 version range:*)
| +- svgwrite(install version:1.4 version range:*)
| +- whitenoise(install version:5.0.1 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_django_** to be **_>=2.2.12_**.
2.	Remove your direct dependency **_django_**, and use the **_django_** transitively introduced by **_django-rest-framework_**.
3.	Change your direct dependency **_django-rest-framework_** to be **_>=3.9.2,<=3.11.0_**.
@terceiro  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by mwasilew** [comment]
@NeolithEra so there is no problem 'yet' I assume? If so I wouldn't do any changes. SQUAD probably doesn't work with django 3 (I didn't try) so we need the limitation on the version. django 1.11 is no longer supported and that is most likely the reason to move to 2.2 which is LTS. It will be supported till April 2022 so I see no reason to do any immediate changes.

**Comment by jscook2345** [comment]
@mwasilew This is a bot reporting the issue.

**Comment by mwasilew** [comment]
@jscook2345 I know, and it's wrong.
