### ISSUE TITLE
Server Error on builds comparion when picking n/a tests

### ISSUE THREAD

**Issue by amrohassaan** [Linaro/squad#738]
from builds view picking two builds to compare and then checking the n/a checkbooks renders a server error.

**Comment by mwasilew** [comment]
```RAW_URI = '/_/comparebuilds/?target=v5.6.14-122-g0215fac231ee&project=lkft%2Flinux-stable-rc-5.6-oe&transitions=None&baseline=v5.6.14-121-g8f40203f4915&page=None&transitions=pass%3Afail&transitions=pass%3An%2Fa&transitions=fail%3Apass'```

Problem is with ```transitions=None```. It's either backend that needs to be adjusted, or frontend should pass ```None:None``` or thereabout.

**Comment by chaws** [comment]
It was in the backend: transitions are passed to query string every time, and when page is loaded I had to clean the url from "transitions", bug was that transitions was assigned to None, instead of being removed from the querystring. Fixed now :)

**Comment by chaws** [comment]
Fixed in #744
