### ISSUE TITLE
Timeout when deleting build

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#741]
Deleting build times out in admin view.

**Comment by mwasilew** [comment]
It's the same with some testruns, testjobs, projects and groups if they have a lot of test results. The issue is admin UI tries to list all objects to delete. If there are loads of test/metric objects all of them get listed. Can we prevent this?

**Comment by chaws** [comment]
Have no clue, I bet that there's some option to prevent that page from loading objects. I'll check it

**Comment by mwasilew** [comment]
There are a few options: https://code.djangoproject.com/ticket/10919

**Comment by chaws** [comment]
Fix in https://github.com/Linaro/squad/pull/766

**Comment by chaws** [comment]
@mwasilew thanks for the pointer! I used that to find the solution.
