### ISSUE TITLE
Test case results comparison broken old link

### ISSUE THREAD

**Issue by nareshkamboju** [Linaro/squad#758]
With the new squad release, The changes to test results comparison has changed.
I have reported handful of bugs with quoting qa report test results comparison of a given branch
These kind of listed links are broken now when viewed by external and internal users from Bugzilla and upstream email reports which i shared.

https://qa-reports.linaro.org/lkft/linux-stable-rc-4.4-oe/tests/ltp-syscalls-tests/fanotify10
https://qa-reports.linaro.org/lkft/linux-stable-rc-4.9-oe/tests/ltp-syscalls-tests/fanotify10
https://qa-reports.linaro.org/lkft/linux-stable-rc-5.6-oe/tests/ltp-syscalls-tests/clock_gettime03
https://qa-reports.linaro.org/lkft/linux-mainline-oe/tests/ltp-mm-tests/shmt03
https://qa-reports.linaro.org/lkft/linux-mainline-oe/tests/kselftest/net_forwarding_bridge_igmp.sh
and many more

- Naresh

**Comment by mwasilew** [comment]
@nareshkamboju you're right. This is unfortunate. Luckily it's pretty easy to fix. The links will be back next week. Right now we have links for the actual build that can show the failure. Example:
https://qa-reports.linaro.org/lkft/linux-stable-rc-4.4-oe/build/v4.4.226-37-g61ef7e7aaf1d/testrun/2806891/suite/ltp-syscalls-tests/test/fanotify10/details/
and history view (the one that is missing):
https://qa-reports.linaro.org/lkft/linux-stable-rc-4.4-oe/build/v4.4.226-37-g61ef7e7aaf1d/testrun/2806891/suite/ltp-syscalls-tests/test/fanotify10/history/

**Comment by nareshkamboju** [comment]
@mwasilew  Thanks for your reply.
I have noticed history view for comparison.
OTOH, Test results comparison between projects also not working.
For example like this one,
https://qa-reports.linaro.org/_/comparetest/?project=22&project=232&project=284&project=310&suite=ltp-syscalls-tests&test=fanotify01

**Comment by mwasilew** [comment]
@nareshkamboju let's not mix things. Could you report it separately?

I would also suggest using test details view rather than history for reporting issues. It contains more details about the actual failure then history view.

**Comment by nareshkamboju** [comment]
@mwasilew you are right !
I have been using the actual test failure log in plan text while reporting.
I will report a separate issue.
