### ISSUE TITLE
RFC: test/metric model changes

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#777]
Hi,

**cc**: @mwasilew @terceiro @amrohassaan 

## The issue
Lately we've been having some pages that are taking an enormous time to load. They are pages that need to gather all tests that belong to a given build, like test history and compare test view.

## The problem
Because there's no direct relation between builds and tests, a test_run join needs to take place, making queries run slow. I was able to work around that join by fetching tests using batches of test_run ids (https://github.com/Linaro/squad/blob/1.15.1/squad/core/comparison.py#L192) but I think this is not optimal.

The very same happens when gathering list of metrics of a given project. For that to happen, there need to be a list of all builds from a project, then grab test runs from each build to finally join the metric table. Visiting "metrics" in production just almost never work or takes a huge amount of time to load the main page.

### Part 1
My idea is very simple but a bit dumb. It's simple because it would make Test have a foreign key for its Build. It's dumb because it'll be denormalizing the DB. In my opinion, this is a very isolated specific solution, given that in production we're almost at **half a billion** tests. My hypothesis is that it'll eliminate test run joins in favor of a single `WHERE build_id = id` therefore making queries faster.

### Part 2
A second change to Test table is to make metadata mandatory. This way we could safely remove the name index and remove the name column completely from that table. Again, think of 500 million test names that could fit in just a couple hundred thousand in SuiteMetadata table. Getting rid of name index would release at least 66G from our current db. I assume that removing name column would clear lots of space as well.

Thoughts?

**Comment by terceiro** [comment]
I don't think the denormalization would be a big problem - because once created, the rows in the tests table are effectively read-only, so the risk of such a build_id FK becoming a data consistency problem is pretty low. fs that gives us an easy performance gain, I would go for it. Now, given the current size of the tests table, this would require some creativity in designing a migration strategy, becausing inserting a value into half a billion rows will take a while :-)

**Comment by amrohassaan** [comment]
@chaws apologies for seeing this late. Your two suggestions makes sense and I agree with @terceiro that since tests table are sort of leaf node in our models tree, ending up having a non normalized issue there will be low risk.  Just looking out for the future of SQUAD, the only concern for it as an OSS project is: will we leave it this way with a denormalized tabel or do we have a longer term strategy to revamp the relations between our models re-funnelling back our lesson learned into a newer design...but again this is a very long-term and low-priority concern.

**Comment by chaws** [comment]
Thanks @amrohassaan , @terceiro for feedback!

I thought about making this change in a few steps:
1. add build_id FK with NULL=True, without using it yet
1.1. change the code to write build_id to Tests, without using it yet
2. create data migration to fill build_id accordingly, while still not using it
2.1. Do this in batches while running Vacuum. From [here](https://dba.stackexchange.com/q/21014), I got
> PostgreSQL utilizes MVCC to provide concurrent access to table data. Under this scheme, each update creates a new version  of the row that was updated (this could be via time stamp or version number, who knows?). The old data is not immediately  deleted, but marked for deletion. The actual deletion occurs when a VACUUM operation is performed.
3. make NULL=False for build_id (that's the part that worries me most)
4. change code to start using build_id

Anyways, I can experiment locally as I have a dump of production database. I'll finish up the k8s stuff then start experimenting with db

**Comment by chaws** [comment]
@terceiro fyi this is [almost] completely done, it was a bumpy path as you predicted (somehow you can foresee the future), but I managed to make it (hopefully correct). All steps required are listed just for the record:

0. Update note: we don't just keep half a billion tests, now we're dealing with **+1 billion**, so this adds up more fun to it
1. [Added build and environment to test](https://github.com/Linaro/squad/pull/922): the migration took about 2h just to add build and environment id field with NULL value in it. The long time was due to index build (one for build_id and one for environment_id)
2. [Run the command to actually populate build and environment ids](https://github.com/Linaro/squad/blob/1.33/squad/core/management/commands/populate_test_build_and_environment.py), this took about 2 days to finish (10 threads)
  2.1. As consequence, this doubled the size of the test table thus generating an insane number of dead tuples (due to how postgres implements UPDATEs)
  2.2. The abnormal number of dead tuples caused access to test table to slow down, while the expected behavior was the exact opposite. It has something to do how postgres saves records in blocks of 8Kb in the file system. Because now it needs to load much more blocks to get the same number of "live" tuples.
  2.3. Solution was to fully rebuild the test table with minimum downtime. The [pg_repack extension](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.pg_repack) had it nicely done in a bit over 20ish hours. After that access times came back to normal.
3. This allowed some performance improvements to be patched in:
  3.1. [Faster and lighter regressions and fixes](https://github.com/Linaro/squad/pull/929) computation makes [ProjectStatus.create_or_update()](https://github.com/Linaro/squad/blob/1.33/squad/core/models.py#L1102) avoid [loading all tests into memory](https://github.com/Linaro/squad/issues/906) saving time in serialization and memory allocation (fetch workers shouldn't require more than a few hundred MBs). Some cases we had workers allocating over 5G of ram when processing [builds with +1.5M tests](https://qa-reports.linaro.org/android-lkft/5.4-gki-android11-android11-db845c-presubmit/).
  3.2. Direct way (no JOINs) of getting Build tests by [adding endpoint to builds api](https://github.com/Linaro/squad/pull/927), fixing a [1-year-old issue](https://github.com/Linaro/squad/issues/634) that used to make squad "slow". Now, along with the ability to [hand-pick object's fields from the API](https://github.com/Linaro/squad/pull/916), we're able to retrive thousands of build tests in matters of seconds!

Notes:
1. All operations were made with close-to-0 downtime
2. [pg_repack](https://reorg.github.io/pg_repack/) is an awesome tool!
3. I mentioned that the work is almost complete because it still not replicated for metrics. I'll do that sometime next year. It's a good thing that we don't have a billion of those [yet].

**Comment by terceiro** [comment]
nice :partying_face:
