### ISSUE TITLE
Cannot resubmit a test job ("zephyr-upstream") project

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#779]
Steps to reproduce:

1. Visit a "test jobs" page like https://qa-reports.linaro.org/lite/zephyr-upstream/build/95717db0-5336/testjobs/
2. Find an incomplete job (with a red cross on the left). (Note: resubmission fails for any job, resubmitting incomplete jobs just an expected "makes-sense" usecase).
3. In this case, let that be "2049149" (2nd from top).
4. Click "resubmit" button.
5. Behold an alert box with "There was an error while resubmitting. Status = 403 Forbidden(complete)" appear.
6. For completeness, click also "force resubmit" button and watch the same alert box appear.

**Comment by pfalcon** [comment]
Of related note:

7. Note that as user, you have no idea what's the difference between "resubmit" and "force resubmit" buttons.
8. Imagine, that it might make sense to show only one of these 2 buttons, but not 2 at the same time. I.e., if it's possible to just "resubmit" a job, then "force resubmit" probably doesn't make much sense. And vice versa, when normal resubmit isn't possible/doesn't make sense, a "forced resubmit" still may have.

**Comment by mwasilew** [comment]
most likely a permission issue. Let me check.

**Comment by pfalcon** [comment]
Forget to mention that at the time of those actions, I'm logged into validation.linaro.org if that may matter (it hardly would do, would require explicit cross-site sign-on or something).

Also reminds me that I actually raised a (theoretical) question on related matter in https://github.com/Linaro/squad/pull/691, and now hit practical implications.

**Comment by mwasilew** [comment]
@pfalcon logging in to lava makes no difference here. I assume you're logged into squad when making such request. Am I correct?

**Comment by mwasilew** [comment]
@pfalcon are you able to access this URL: https://qa-reports.linaro.org/api/testjobs/3046307/ ?

**Comment by pfalcon** [comment]
> I assume you're logged into squad when making such request. Am I correct?

Yes, sure.

**Comment by pfalcon** [comment]
> are you able to access this URL: https://qa-reports.linaro.org/api/testjobs/3046307/ ?

Yes. Do you want me to try "/resubmit" action via API?

**Comment by mwasilew** [comment]
> > are you able to access this URL: https://qa-reports.linaro.org/api/testjobs/3046307/ ?
> 
> Yes. Do you want me to try "/resubmit" action via API?

yes, please. This will show where the issue is. I guess you don't have enough permission to create new TestJob object which resubmit action does.

**Comment by mwasilew** [comment]
The issue was lack of django access rights to create TestJob objects. IMHO this should be addressed in #740

**Comment by pfalcon** [comment]
In the meantime, I confirm that now I can resubmit a job by clicking the button. If there's a focused ticket to address the underlying issue, I guess let's close this, I just would ask, @mwasilew, to check that permission for @galak too. Thanks!

**Comment by mwasilew** [comment]
This issue should be fixed in the code as well now.
