### ISSUE TITLE
Restrict backends to specific groups

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#808]
After a talk with Anders he raised a concern: anyone submitting jobs thru squad can use any backend. He questioned if there was a way to limit a backend to a single group, in order to prevent anyone else from using a backend.

**Comment by mwasilew** [comment]
IMHO this isn't a problem. Why would you limit usage of backend?

**Comment by chaws** [comment]
I think Anders' concern is people using lkft boards without permission. Could you tell us that use case @roxell ?

**Comment by chaws** [comment]
Multi-login will become available soon, if we see that there's bad use of backend resources, then we'll come back to this
