### ISSUE TITLE
testjobs tab listing 25 jobs bump to 50 or 100

### ISSUE THREAD

**Issue by nareshkamboju** [Linaro/squad#814]
testjobs tab listing only 25 jobs bump to 50 or 100.
Each build testing around 300 jobs and In many cases
I have to browse the missing jobs results from the "testjobs".

For easy browsing please increase the number of entries from 25 to 50 or 100.
or provide a drop down box to increase number of jobs in a page like LAVA do.

**Comment by nareshkamboju** [comment]
reference link,
https://qa-reports.linaro.org/lkft/linux-stable-rc-5.8-oe/build/v5.8.1/testjobs/

**Comment by mwasilew** [comment]
@nareshkamboju this hits database hard and we're currently investigating ways of improving the performance. I wouldn't expect this feature to happen any time soon.

**Comment by chaws** [comment]
@mwasilew maybe order testjobs by not-fetched first?

**Comment by mwasilew** [comment]
@chaws proper solution IMHO would be to add filtering options to the list, so you could filter by any parameter. At the moment it's low on my priority list. If @amrohassaan can get to it, he can propose something.

**Comment by mwasilew** [comment]
@nareshkamboju how about this:
![testjob_filters](https://user-images.githubusercontent.com/618901/91174883-cecb2b80-e6d7-11ea-9474-f97331eba9db.png)
I'm planning to hide the filter section by default and only leave labels showing current filter. Will this solve your problem?

**Comment by nareshkamboju** [comment]
@mwasilew The proposed solutions looking good to me.
Thank you +1
