### ISSUE TITLE
Make all users able to create/view/change Projects

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#835]
@roxell asked this feature so that other users can use gitlab-ci pipeline to create projects in qa-reports via squad-client api calls.
@mwasilew any thoughts? I'm rolling out a release today, and planning on doing this tomorrow

**Comment by mwasilew** [comment]
@chaws hmm, isn't it already possible? They need to be group admins.

**Comment by chaws** [comment]
They can manage projects fine via UI, but object-level permission is needed via API, just like testjobs.
I think I can extend @amrohassaan 's change and include project rights as a default group to users?

**Comment by mwasilew** [comment]
I thought that all users have proper access rights now. If this isn't the case, then it's a bug.

**Comment by chaws** [comment]
@mwasilew there
