### ISSUE TITLE
Squad callback/webhook feature

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#842]
This is a request to provide a callback/webhook to be fired on the specific events like 'build completed', 'build created' or 'testjob completed'. More details with proposed design to follow.

**Comment by chaws** [comment]
Just for inspiration: https://developer.atlassian.com/server/jira/platform/webhooks/

**Comment by chaws** [comment]
Closed in https://github.com/Linaro/squad/pull/951

Currently callbacks are supported for Builds only. It's easy to extend it to more classes and more events
