### ISSUE TITLE
Wrong set of log lines for test

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#843]
I think this is not squad-related, but I wanted to write it down before I placed it in the right place (probably in LAVA):

[This test](https://qa-reports.linaro.org/lkft/linux-next-master/build/next-20200915/testrun/3198585/suite/kselftest/test/kvm_vmx_preemption_timer_test/details/) has log:

```
- {"dt": "2020-09-15T09:36:09.094324", "lvl": "target", "msg": "selftests: kvm_svm_vmcall_test [SKIP]"}
```

which is weird. Looking at the [LAVA job](https://lkft.validation.linaro.org/results/testcase/385286989), line number for that test is 11212, which doesn't belong to `kvm_vmx_preemption_timer_test` test. So it must be some bug in LAVA. Log should've been [this line](https://lkft.validation.linaro.org/scheduler/job/1765604#L11205) instead.

My guess is that due to some tests that were skipped LAVA got confused in knowing test's correct line.

cc: @roxell @ivoire

**Comment by ivoire** [comment]
It's LAVA's fault but not fixable. In fact LAVA is using pexpect to match DUT output. pexpect is unable to match line per line so the line number is a best effort. It happens that the line number is wrong but I don't see a way to fix that.
