### ISSUE TITLE
Generate metrics charts server-side and provide permalink 

### ISSUE THREAD

**Issue by amrohassaan** [Linaro/squad#855]
Metrics charts in projects need to be included in external reports and a permalink to the generated chart need to be generated as well. With the current way (charts.js) this is not possible and not available to squad-client.

**Comment by chaws** [comment]
Maybe we can avoid charts all alone in squad and have an external service do that, e.g. ElasticSearch? Let's discuss this in the future

**Comment by stevanradakovic** [comment]
After an email discussion we concluded that there is lack of interest for this feature coming from the stakeholder, ergo closing for the time being.
