### ISSUE TITLE
unable to install squad without postresql installed, blocks testing of squad-client

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#878]
cc: @chaws 

I think we chatted about this before, but I could not recall. Can't search my IRC history ;)

Testing `squad-client` starts up a `squad` instance using sqlite instead of postgresql. So when I try to install `squad` as a dependency to testing `squad-client`, I get the below error. The suggestion in the error says to use `psycopg2-binary` instead. Maybe that is a fix?

How best can we avoid the issue?

```
Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/justin/GitHub/squad-client/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-install-25y7o_6n/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-install-25y7o_6n/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq
         cwd: /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-install-25y7o_6n/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq/psycopg2.egg-info
    writing /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/72/c83rxnn10slcg8tbn_1gxf7r0000gn/T/pip-pip-egg-info-0zmawafq/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by chaws** [comment]
What are the steps you do to get to this?

**Comment by jscook2345** [comment]
In `squad-client`

```
❯ rm -rf .venv

❯ python3 -m venv .venv

❯ source .venv/bin/activate

❯ pip install -r requirements-dev.txt
```

Same thing occurs if you just `pip install squad` as well.

**Comment by chaws** [comment]
Hum, don't use `venv`, I had to install it. When I run your steps I get no error:

https://pastebin.linaro.org/view/83bf0db8

Though, I see all dependencies are coming from cache

**Comment by chaws** [comment]
This time I ran `pip install  --no-cache-dir -r requirements-dev.txt`: https://pastebin.linaro.org/view/1411193f

No cache used, and psycopg2 was installed. Maybe you're missing `sudo apt install python3-psycopg2`?

**Comment by jscook2345** [comment]
The error says it cannot find the binary `pg_config`, which is a part of the `postgresql` package.

I'd like to avoid installing that if possible since I'm only testing with `sqlite`.

**Comment by chaws** [comment]
@jscook2345 please check: https://github.com/Linaro/squad/pull/881

This way `pip install squad` won't install psycopg2, if that's required one would run `pip install squad[postgres]`

**Comment by jscook2345** [comment]
@chaws 

Hmm. I don't think I want to go that far as it will be confusing to people installing `squad` I think. Even with the docs. Please close the PR but leave this issue open as I explore my options.

**Comment by chaws** [comment]
@jscook2345 I think it's OK. This will make squad run easier than with psycopg2 required as dependency. Just like Django supports sqlite by default, and if further databases are required, users should handle dependencies accordingly. I won't affect qa-reports because we already install binaries via debian package manager.

**Comment by jscook2345** [comment]
@chaws 

If you think it is reasonable then I'm fine with it. Thanks so much!
