### ISSUE TITLE
gerrit plugin fails to submit a review

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#894]
I'm getting this message:
```
[WARNING] patch_id "6649/20" for build "49671" failed to match ".+[:,].+"
```
I think the regex is wrong. Docs ask for change_id/patchset as patch_id, which is there. So the regex can't be correct.

**Comment by chaws** [comment]
Hum, i need to dig it deep what's happening there, regex seems correct: https://github.com/Linaro/squad/blob/master/squad/plugins/gerrit.py#L52

**Comment by chaws** [comment]
Ops, it's in another line, fixing it!
