### ISSUE TITLE
Make possible to pick api object fields

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#903]
Currently when retrieving objects from the API, squad returns the full attribute list of objects, it would be nice to select which fields to fetch, in case just a few is needed.

The idea is based on this: https://stackoverflow.com/a/23674297

It'll help squad-client fetch only wanted fields https://github.com/Linaro/squad-client/issues/72

**Comment by amrohassaan** [comment]
@jscook2345 said this will be *nice to have* but is not exactly what they require. Should we keep it?

**Comment by mwasilew** [comment]
This is very little work for a nice feature. I think it's worth it.
