### ISSUE TITLE
Delete storage files as TestRun and Attachment objects get deleted

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#907]
I've learned that When a testrun gets deleted, its storage files aren't, this might become a hassle in the long run when having lots of orphan files.

**Comment by mwasilew** [comment]
is this a "feature" of boto3 or django FileField?

**Comment by chaws** [comment]
Apparently it's Django's "feature": https://stackoverflow.com/questions/5372934/how-do-i-get-django-admin-to-delete-files-when-i-remove-an-object-from-the-datab

I'll add this signal in the same PR I'm working on
