### ISSUE TITLE
Comparison of build tests is not very useful

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#909]
We are now submitting build tests to `squad`, and this is showing us some things that may need adapting. This isn't a high priority item and probably requires additional discussion.

Raised by @roxell

example:

https://qa-reports.linaro.org/_/comparetest/?project=459&suite=build&test=gcc-9-defconfig-50bba0f5

When comparing the result of a build test, it does not make sense to compare the result against many architectures. It would make more sense to compare the test over time or changes to the build config.

**Comment by mwasilew** [comment]
Hmm, when we discussed this with @roxell and @mrchapp they both agreed comparison across architectures is what they wanted.

**Comment by jscook2345** [comment]
@mwasilew I will add it as a discussion item for our KVT meetings and see what comes of it.

**Comment by chaws** [comment]
@jscook2345 any updates on this?

**Comment by jscook2345** [comment]
Closing for now. Maybe we can revisit later.
