### ISSUE TITLE
Poll keeps fetching jobs that aren't ready

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#914]
When a TestJob gets submitted, it'll wait for the backend to signal when it's ready to fetch.

If the backend doesn't signal that before the next poll (every hour), the TestJob will be fetched anyways, or at least it'll be an attempt.

I think the poll task could do a pre-check of the TestJob status prior to call `fetch` on it.

**Comment by mwasilew** [comment]
It's already done: 
https://github.com/Linaro/squad/blob/master/squad/ci/backend/lava.py#L109

**Comment by chaws** [comment]
Ahh, yeah, that'll do it

I thought that the 502 error might have been happening due to that, please ignore
