### ISSUE TITLE
IndexError: list index out of range on submit

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#919]
I got this from sentry:

```python
IndexError: list index out of range
  File "squad/ci/tasks.py", line 37, in submit
    test_job.backend.submit(test_job)
  File "squad/ci/models.py", line 149, in submit
    test_job.job_id = job_id_list[0]
```

This was due a 408 error `POST https://lavalab.nxp.com/api/v0.2/jobs/ [408] reason: Request Timeout`

And because of that, the job_id list might be an empty list https://github.com/Linaro/squad/blob/1.28.2/squad/ci/backend/lava.py#L362 and here for resubmit https://github.com/Linaro/squad/blob/1.28.2/squad/ci/backend/lava.py#L349

I'll work up a patch for this tomorrow

**Comment by chaws** [comment]
@amrohassaan 

This seems to be a "different" type of timeout. I just found that there's already a check for timeout on job submit: https://github.com/Linaro/squad/blob/master/test/ci/backend/test_lava.py#L436

but I don't know why the `408` timeout didn't raise an exception.

**Comment by mwasilew** [comment]
I briefly checked requests code and it seems they don't raise exception on 408 response. This means we need to handle 408 response on our side.
