### ISSUE TITLE
[Usability] Can't immediately see number of testcases on the "build details" page

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#924]
Steps to reproduce:

1. Visit a project's main, listing recent builds, e.g. https://qa-reports.linaro.org/lite/lite-tf-m/ .
2. You can see a number of testcases for each build, screenshot attached:
![Screenshot at 2020-12-03 12-34-02](https://user-images.githubusercontent.com/500451/100991280-7f5c8d00-355b-11eb-9901-bce54e642c6d.png)
3. Click on a particular build, e.g. "b157dca4-130" on the page above.
4. On the build info page which opens, you no longer see the figure "108" anywhere!

To see it, you need to make extra manipulation (about which you should know!), e.g. uncheck the "failures only" checkbox. That's a usability issue, "build details" page clearly should not show less info than "builds listing" page.

I literally hit this when preparing to submit another bug, and was reciting reproduction steps for it - clear and concise, which now will be less clear and concise ;-).

**Comment by chaws** [comment]
@amrohassaan I think that summary is a sub-include, so it's just a matter of including that to the top of the build page?

**Comment by chaws** [comment]
@pfalcon sorry, little late on this: https://github.com/Linaro/squad/pull/985

Do you have a better idea where to add the summary in the build page? I tried adding it next to "All test results" tab, but it got super messy.
