### ISSUE TITLE
testrun status seems odd in the api, perhaps I am using it wrong

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#944]
Not exactly sure what the `testrun` `status` is, but I had been using it to generate a summary of test results.

However, I noticed some of our build tests are generating odd statuses.

See:
https://qa-reports.linaro.org/api/testruns/3582611/status/

and compare to:
https://qa-reports.linaro.org/lkft/linux-next-master/build/next-20201214/testrun/3582611/suite/build/tests/

Why are there 3 `status`? Why does one have a null suite? Why does no.3 `status` (14) add up to no.1 and no.2 `status` for `tests_pass`? (6+8=14) coincidence?

**Comment by chaws** [comment]
Will try to answer your questions, let me know if it's not clear:

Each status == summary per suite, and suite=None means overall summary across all suites. 

For testrun https://qa-reports.linaro.org/api/testruns/3582611/status/ there are 2 status for suites: one for [suite 7338 (build)](https://qa-reports.linaro.org/api/suites/7338/) and one for [suite 47906 (linux-log-parser)](https://qa-reports.linaro.org/api/suites/47906/). 

The third status (suite=null) combines all suites' statuses: 6 from build suite and 8 from linux-log-parser that adds 14, so not a coincidence :p 

We store those to present overall summaries in the frontend.

If you'd like to see a status for a single suite, you can use filters: https://qa-reports.linaro.org/api/testruns/3582611/status/?suite=7338 (I guess documentation is taking a higher priority in our list)

**Comment by jscook2345** [comment]
Thanks for the answer. That is clear now.
