### ISSUE TITLE
ordering="slug" does not work for tests.short_name

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#952]
From my discussion with @chaws 

```
build.tests(environment=e.id,suite=s.id,ordering="short_name")
```
does not appear to be working for the ordering component. it appears to be ordering by `id`.

Is this the issue? https://github.com/Linaro/squad/blob/9472d5e337a38488d1fb44c986deec7e8a54d6e7/squad/api/rest.py#L1161 only the `id` is there and thus can't be filtered on other things?

**Comment by chaws** [comment]
I looked at the code and it won't be that easy to via api. Tests are complicated as they're are just too much and we need to order them by id so we can make cursor pagination.

I'll make a generic function in squad-client so you can call it on demand, does that sound good?

**Comment by chaws** [comment]
Moved to https://github.com/Linaro/squad-client/issues/107
