### ISSUE TITLE
timeout when trying to delete my group

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#972]
I wanted to reset my test projects and data in squad, so I went to delete my group `~justin.cook`. I got a `504` error with a timeout response from `squad`. It *looks* like nothing happened, but I wonder if maybe something did and things might be in an inconsistent state.

**Comment by jscook2345** [comment]
I was able to delete individual projects within my group OK, but that is a bit time consuming.

**Comment by chaws** [comment]
I thought this was already implemented here: https://github.com/Linaro/squad/commit/6da1b578affde407111bf6293871da43f71c33d1

Will double check that

**Comment by chaws** [comment]
Ahh, you did it in the "Group settings" tab, I'm betting, there's no implementation for that :) It should be easy to fix this
