### ISSUE TITLE
Reference build "stuck", getting constant email notifications against it

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#975]
For https://qa-reports.linaro.org/lite/zephyr-micropython/ , I'm getting email notifications every day with the following summary: `lite/zephyr-micropython: 609 tests, 0 failed, 381 passed,  228 skipped` (same every day) and following change higlight:

![Screenshot at 2021-04-07 12-09-18](https://user-images.githubusercontent.com/500451/113841182-223b4700-979a-11eb-9903-4b5312035e60.png)

As can be seen, `#1514` build was selected as a comparison reference, which happened to have failed. Following builds succeeded, but as they get compared with `#1514`, email notification is sent with differences.

But the issue is that the reference build itself should be updated to a newer build, and that doesn't happen.

**Comment by chaws** [comment]
I've subscribed myself to the notifications so I can get it the next time.

I'm looking into it now

**Comment by chaws** [comment]
Squad will send you a report of a build when it's finished or after a certain timeout, which is 6 hours for lite/zephyr-micropython.

In the report/email, squad will compare the current build against the most recent finished build. A build is finished when all its Jobs are done in LAVA. From what I checked, the most recent one is #1514.

All builds after #1514 have not received any answer from LAVA wrt disco-l475-iot1 jobs. It seems that this device is not available in LAVA: https://validation.linaro.org/scheduler/device_type/disco-l475-iot1

**Comment by pfalcon** [comment]
@chaws: Thanks for investigating! Ack on disco-l475-iot1 being down. I have 2 questions:

> Squad will send you a report of a build when it's finished or after a certain timeout, which is 6 hours for lite/zephyr-micropython.
> In the report/email, squad will compare the current build against the most recent finished build.

1. Why "after a certain timeout (which is 6 hours here)" rule doesn't apply to determination of "finished build". I'd say, that would be intuitive behavior I'd expect: if I set timeout to 6 hours, I'd like it to be "finished" in 6 hours, repsonsed received, or not. In other words, is there any issue to fix on SQUAD side, or we just learn to manually update SQUAD's project config for such situation?
2. How to update SQUAD's project config to workaround this issue. I.e., we'd like to mark disco-l475-iot1 as "don't consider"/"don't expect results". (The devices have hardware problems, we expecte them to be recovered, but ETA is not known currently, i.e. can be a few months).

Thanks!

**Comment by chaws** [comment]
> 1. Why "after a certain timeout (which is 6 hours here)" rule doesn't apply to determination of "finished build". I'd say, that would be intuitive behavior I'd expect: if I set timeout to 6 hours, I'd like it to be "finished" in 6 hours, repsonsed received, or not. In other words, is there any issue to fix on SQUAD side, or we just learn to manually update SQUAD's project config for such situation?

We've always been trying to determine a better way for a build to finish faster and never got to an ideal solution, but I think your suggestion is really good. Let me work on that.

> 2. How to update SQUAD's project config to workaround this issue. I.e., we'd like to mark disco-l475-iot1 as "don't consider"/"don't expect results". (The devices have hardware problems, we expecte them to be recovered, but ETA is not known currently, i.e. can be a few months).

That can be done. Since Squad uses job status to determine a finished build, I could come up with a patch that reads the "expected test runs" in an environment, if it's -1, then I ignore the status of all jobs for that environment. I think that can also be used to prevent Squad from submitting jobs for that environment.

**Comment by pfalcon** [comment]
@chaws: Thanks for supporting this idea and looking into it further!

> the first one will add a new flag in project settings called Force finishing builds on timeout, that, when enabled, will mark builds as finished when "Notification timeout" is reached.

I looked thru the existing "project settings", and agree that's the most natural way to do it, to not change behavior behind backs of existing projects, and yet intuitively extend the meaning of the existing timeout.

> the second one is about disabling environments. While that's simple to implement, I just wanted to double check with you if this won't break any of your CI systems. Disabling environments will return 401, aka bad request when you try to submit a job to that environment in Squad. Do your CI handles that OK?

That should be ok. In the case of disco-l475-iot1 mentioned above, I already disabled submitting jobs from Jenkins to LAVA (via qa-reports). And it seems to make sense that if an environment is disabled in SQUAD, then error out if a job submitted to it (instead of silently dropping it).

**Comment by chaws** [comment]
@pfalcon , sorry for delay. Both of these features are released now!

**Comment by pfalcon** [comment]
@chaws: Thanks much for prompt resolution of these! I was distracted by some other things, configuring these params for our projects now...

**Comment by pfalcon** [comment]
Submitted https://github.com/Linaro/squad/issues/983 with minor cosmetic improvement suggestion.
