### ISSUE TITLE
dead socket with lkft.v.l.o

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#976]
The backend connection with lkft.validation.linaro.org was dead, and the listener didn't detect that.

This caused all jobs from lkft.v.l.o to be fetched during poll, e.g. every hour, thus causing delays in other CI pipelines

reported by @jscook2345

**Comment by jscook2345** [comment]
As a part of this issue, please add it to the status page that you're working on per our conversation. Thanks again @chaws !

**Comment by chaws** [comment]
The dead sockets seems to be fixed in https://github.com/Linaro/squad/commit/e184edcd75dee3c643821fa149e0168a19b08cad

regarding the status page, I think I'm going with https://github.com/Linaro/squad/pull/984, that's the best I could come up with little changes in the code. Adding lab connections statuses would involve a more significant amount of work, as in the background these are running in separate nodes
