### ISSUE TITLE
Project settings: Consider package "force finishing builds" together with related "notification_timeout" setting

### ISSUE THREAD

**Issue by pfalcon** [Linaro/squad#983]
This is a follow up to https://github.com/Linaro/squad/issues/975 and specifically commit https://github.com/Linaro/squad/commit/c62fac1cae26581fabfa157e15872ad52e109b49.

On a page like https://qa-reports.linaro.org/lite/zephyr-micropython/settings/ , I would expect thew newly added "Force finishing builds on timeout" form field to go immediately after the "Notification timeout", as they're logically connected. However, currently the "Force finishing builds on timeout" option is shown at the very end of the form.

**Comment by chaws** [comment]
Done here: https://github.com/Linaro/squad/commit/6455904be35cb209291337d4f1eb44c70f0a54ac

I'll keep you posted when this is released.

Thanks for the feedback!
